#pragma once

#ifndef TUBES_ENABLE_DIG2GO_PEER_PROPAGATION
#define TUBES_ENABLE_DIG2GO_PEER_PROPAGATION 0
#endif

#if defined(TUBES_DIG2GO_LEGACY_PULL_HOST) && !TUBES_ENABLE_DIG2GO_PEER_PROPAGATION
#error "TUBES_DIG2GO_LEGACY_PULL_HOST requires TUBES_ENABLE_DIG2GO_PEER_PROPAGATION"
#endif

#if defined(TUBES_DIG2GO_DYNAMIC_ENROLLMENT) && !defined(TUBES_DIG2GO_LEGACY_PULL_HOST)
#error "TUBES_DIG2GO_DYNAMIC_ENROLLMENT requires TUBES_DIG2GO_LEGACY_PULL_HOST"
#endif

#if defined(TUBES_DIG2GO_LEGACY_PULL_HOST) && !defined(TUBES_DIG2GO_DYNAMIC_ENROLLMENT)
#error "Dig2Go peer pull hosting requires dynamic enrollment"
#endif
