#pragma once

#include <stdint.h>
#include <string.h>

#include "device_report_protocol.h"

// AI: below section was generated by an AI
// Internal admission contract only. This structure is deliberately not packed,
// serialized, or assigned a mesh action key; Steve's wire protocol remains the
// authority for how these facts are eventually exchanged.
enum FirmwareChipFamily : uint8_t {
  FirmwareChipUnknown = 0,
  FirmwareChipEsp32 = 1,
  FirmwareChipEsp32C3 = 2,
  FirmwareChipEsp32S3 = 3,
};

enum FirmwareFlashMode : uint8_t {
  FirmwareFlashModeUnknown = 0,
  FirmwareFlashModeDio = 1,
  FirmwareFlashModeQio = 2,
  FirmwareFlashModeOpi = 3,
};

struct FirmwareTargetContract {
  uint8_t hardwareFamily = TubeHardwareUnknown;
  uint8_t chipFamily = FirmwareChipUnknown;
  uint8_t flashMode = FirmwareFlashModeUnknown;
  uint32_t flashSizeBytes = 0;
  uint32_t otaSlotOffset = 0;
  uint32_t otaSlotSizeBytes = 0;
  uint8_t partitionTableSha256[32] = {0};
};

enum FirmwareTargetMatch : uint8_t {
  FirmwareTargetMatchExact = 0,
  FirmwareTargetUnknown,
  FirmwareTargetHardwareMismatch,
  FirmwareTargetChipMismatch,
  FirmwareTargetFlashModeMismatch,
  FirmwareTargetFlashSizeMismatch,
  FirmwareTargetPartitionMismatch,
  FirmwareTargetOtaSlotMismatch,
};

inline bool firmwareTargetHasPartitionIdentity(const FirmwareTargetContract& target) {
  for (uint8_t value : target.partitionTableSha256) {
    if (value != 0)
      return true;
  }
  return false;
}

inline bool firmwareTargetIsKnown(const FirmwareTargetContract& target) {
  return target.hardwareFamily != TubeHardwareUnknown
      && target.chipFamily != FirmwareChipUnknown
      && target.flashMode != FirmwareFlashModeUnknown
      && target.flashSizeBytes > 0
      && target.otaSlotSizeBytes > 0
      && firmwareTargetHasPartitionIdentity(target);
}

inline FirmwareTargetMatch matchFirmwareArtifactTarget(
    const FirmwareTargetContract& artifactTarget,
    const FirmwareTargetContract& receiverTarget
) {
  if (!firmwareTargetIsKnown(artifactTarget) || !firmwareTargetIsKnown(receiverTarget))
    return FirmwareTargetUnknown;
  if (artifactTarget.hardwareFamily != receiverTarget.hardwareFamily)
    return FirmwareTargetHardwareMismatch;
  if (artifactTarget.chipFamily != receiverTarget.chipFamily)
    return FirmwareTargetChipMismatch;
  if (artifactTarget.flashMode != receiverTarget.flashMode)
    return FirmwareTargetFlashModeMismatch;
  if (artifactTarget.flashSizeBytes != receiverTarget.flashSizeBytes)
    return FirmwareTargetFlashSizeMismatch;
  if (memcmp(artifactTarget.partitionTableSha256, receiverTarget.partitionTableSha256,
      sizeof(artifactTarget.partitionTableSha256)) != 0)
    return FirmwareTargetPartitionMismatch;
  if (artifactTarget.otaSlotOffset != receiverTarget.otaSlotOffset
      || artifactTarget.otaSlotSizeBytes != receiverTarget.otaSlotSizeBytes)
    return FirmwareTargetOtaSlotMismatch;
  return FirmwareTargetMatchExact;
}
// AI: end
