#pragma once

#include <stdint.h>
#include <string.h>

#include "device_report_protocol.h"

// AI: below section was generated by an AI
// Internal admission contract only. This structure is deliberately not packed,
// serialized, or assigned a mesh action key; Steve's wire protocol remains the
// authority for how these facts are eventually exchanged.
enum FirmwareChipFamily : uint8_t {
  FirmwareChipUnknown = 0,
  FirmwareChipEsp32 = 1,
  FirmwareChipEsp32C3 = 2,
  FirmwareChipEsp32S3 = 3,
};

enum FirmwareFlashMode : uint8_t {
  FirmwareFlashModeUnknown = 0,
  FirmwareFlashModeDio = 1,
  FirmwareFlashModeQio = 2,
  FirmwareFlashModeOpi = 3,
};

struct FirmwareTargetContract {
  uint8_t hardwareFamily = TubeHardwareUnknown;
  uint8_t chipFamily = FirmwareChipUnknown;
  uint8_t flashMode = FirmwareFlashModeUnknown;
  uint32_t flashSizeBytes = 0;
  uint32_t otaSlotOffset = 0;
  uint32_t otaSlotSizeBytes = 0;
  uint8_t partitionTableSha256[32] = {0};
};

enum FirmwareTargetMatch : uint8_t {
  FirmwareTargetMatchExact = 0,
  FirmwareTargetUnknown,
  FirmwareTargetHardwareMismatch,
  FirmwareTargetChipMismatch,
  FirmwareTargetFlashModeMismatch,
  FirmwareTargetFlashSizeMismatch,
  FirmwareTargetPartitionMismatch,
  FirmwareTargetOtaSlotMismatch,
};

inline bool firmwareTargetHasPartitionIdentity(const FirmwareTargetContract& target) {
  for (uint8_t value : target.partitionTableSha256) {
    if (value != 0)
      return true;
  }
  return false;
}

inline bool firmwareTargetIsKnown(const FirmwareTargetContract& target) {
  return target.hardwareFamily != TubeHardwareUnknown
      && target.chipFamily != FirmwareChipUnknown
      && target.flashMode != FirmwareFlashModeUnknown
      && target.flashSizeBytes > 0
      && target.otaSlotSizeBytes > 0
      && firmwareTargetHasPartitionIdentity(target);
}

inline FirmwareTargetMatch matchFirmwareTarget(
    const FirmwareTargetContract& sender,
    const FirmwareTargetContract& receiver
) {
  if (!firmwareTargetIsKnown(sender) || !firmwareTargetIsKnown(receiver))
    return FirmwareTargetUnknown;
  if (sender.hardwareFamily != receiver.hardwareFamily)
    return FirmwareTargetHardwareMismatch;
  if (sender.chipFamily != receiver.chipFamily)
    return FirmwareTargetChipMismatch;
  if (sender.flashMode != receiver.flashMode)
    return FirmwareTargetFlashModeMismatch;
  if (sender.flashSizeBytes != receiver.flashSizeBytes)
    return FirmwareTargetFlashSizeMismatch;
  if (memcmp(sender.partitionTableSha256, receiver.partitionTableSha256,
      sizeof(sender.partitionTableSha256)) != 0)
    return FirmwareTargetPartitionMismatch;
  if (sender.otaSlotOffset != receiver.otaSlotOffset
      || sender.otaSlotSizeBytes != receiver.otaSlotSizeBytes)
    return FirmwareTargetOtaSlotMismatch;
  return FirmwareTargetMatchExact;
}
// AI: end
