#pragma once

#include <stdint.h>
#include <string.h>

#include "mesh_protocol.h"

// AI: below section was generated by an AI

constexpr uint16_t FLEET_UPDATE_MAGIC = 0x4654; // "TF" little-endian.
constexpr uint8_t FLEET_UPDATE_PROTOCOL_VERSION = 1;
constexpr uint16_t FLEET_UPDATE_MAX_START_WINDOW_MS = 30000;
constexpr uint16_t FLEET_UPDATE_DEFAULT_PORT = 8080;
constexpr uint8_t FLEET_UPDATE_CREDENTIAL_BYTES = 22;
constexpr char FLEET_FIRMWARE_IDENTITY_MAGIC[8] = {'T', 'U', 'B', 'E', 'U', 'P', '1', '\0'};

enum FleetUpdateFlag : uint8_t {
  FleetUpdateForce = 1 << 0,
  FleetUpdatePropagate = 1 << 1,
};

#pragma pack(push, 1)
struct FleetUpdateOffer {
  uint16_t magic = FLEET_UPDATE_MAGIC;
  uint8_t protocolVersion = FLEET_UPDATE_PROTOCOL_VERSION;
  uint8_t flags = 0;
  uint16_t tubesVersion = 0;
  uint32_t nonce = 0;
  uint8_t serverAddress[4] = {0};
  uint16_t serverPort = FLEET_UPDATE_DEFAULT_PORT;
  uint16_t startWindowMs = 0;
  DeviceId targetDeviceId = 0;
  uint8_t ssidLength = 0;
  uint8_t passwordLength = 0;
  char credentials[FLEET_UPDATE_CREDENTIAL_BYTES] = {0};
};

struct FleetFirmwareIdentity {
  char magic[8];
  uint8_t protocolVersion;
  uint8_t hardwareFamily;
  uint8_t firmwareVariant;
  uint16_t tubesVersion;
  uint8_t reserved[3];
};
#pragma pack(pop)

static_assert(sizeof(FleetUpdateOffer) == 44, "fleet update offer wire size changed");
static_assert(sizeof(FleetUpdateOffer) <= 44, "fleet update offer exceeds the Control body");
static_assert(sizeof(FleetFirmwareIdentity) == 16, "fleet firmware identity size changed");

inline bool isValidFleetUpdateOffer(const FleetUpdateOffer& offer) {
  const uint8_t unknownFlags = offer.flags & ~(FleetUpdateForce | FleetUpdatePropagate);
  const bool propagate = offer.flags & FleetUpdatePropagate;
  const bool hasServer = offer.serverAddress[0] || offer.serverAddress[1]
      || offer.serverAddress[2] || offer.serverAddress[3];
  const bool serveCurrent = propagate && !hasServer && offer.serverPort == 0;
  return offer.magic == FLEET_UPDATE_MAGIC
      && offer.protocolVersion == FLEET_UPDATE_PROTOCOL_VERSION
      && unknownFlags == 0
      && offer.tubesVersion > 0
      && offer.nonce != 0
      && (hasServer || serveCurrent)
      && (offer.serverPort != 0 || serveCurrent)
      && offer.startWindowMs <= FLEET_UPDATE_MAX_START_WINDOW_MS
      && offer.ssidLength <= FLEET_UPDATE_CREDENTIAL_BYTES
      && offer.passwordLength <= FLEET_UPDATE_CREDENTIAL_BYTES
      && uint16_t(offer.ssidLength) + offer.passwordLength <= FLEET_UPDATE_CREDENTIAL_BYTES
      && ((offer.ssidLength == 0 && offer.passwordLength == 0)
          || offer.ssidLength > 0)
      && !(propagate && (offer.flags & FleetUpdateForce))
      && (!serveCurrent || (offer.targetDeviceId != 0
          && offer.startWindowMs == 0
          && offer.ssidLength == 0 && offer.passwordLength == 0));
}

inline bool setFleetUpdateCredentials(
    FleetUpdateOffer& offer,
    const char* ssid,
    const char* password
) {
  size_t ssidLength = ssid ? strnlen(ssid, FLEET_UPDATE_CREDENTIAL_BYTES + 1) : 0;
  size_t passwordLength = password
      ? strnlen(password, FLEET_UPDATE_CREDENTIAL_BYTES + 1)
      : 0;
  if (ssidLength > UINT8_MAX
      || passwordLength > UINT8_MAX
      || ssidLength + passwordLength > FLEET_UPDATE_CREDENTIAL_BYTES)
    return false;
  memset(offer.credentials, 0, sizeof(offer.credentials));
  offer.ssidLength = uint8_t(ssidLength);
  offer.passwordLength = uint8_t(passwordLength);
  if (ssidLength)
    memcpy(offer.credentials, ssid, ssidLength);
  if (passwordLength)
    memcpy(offer.credentials + ssidLength, password, passwordLength);
  return true;
}

inline bool fleetUpdateTargetsDevice(const FleetUpdateOffer& offer, DeviceId deviceId) {
  return offer.targetDeviceId == 0 || offer.targetDeviceId == deviceId;
}

// Stable MAC scheduling spreads connection setup without requiring a fleet roster.
inline uint16_t fleetUpdateStartDelay(
    const FleetUpdateOffer& offer,
    const uint8_t deviceMac[6]
) {
  if (!offer.startWindowMs)
    return 0;
  uint32_t hash = offer.nonce;
  for (uint8_t index = 0; index < 6; index++)
    hash = (hash ^ deviceMac[index]) * 16777619UL;
  return uint16_t(hash % (uint32_t(offer.startWindowMs) + 1U));
}

// AI: end
