#pragma once

#include <stdint.h>

// AI: below section was generated by an AI
// Models the bounded, allocation-free route sidecar used by spatial-aware Tubes.
constexpr uint32_t MOBILE_ROUTE_MAGIC = 0x5452434dUL; // "MCRT" little-endian
constexpr uint8_t MOBILE_ROUTE_VERSION = 1;
constexpr uint8_t MOBILE_ROUTE_SIZE = 24;
constexpr uint32_t MOBILE_ROUTE_ADVERTISEMENT_MS = 500;
constexpr uint16_t MOBILE_ROUTE_FRESHNESS_MS = 3000;
constexpr uint32_t MOBILE_ROUTE_MIN_DWELL_MS = 1500;
constexpr uint16_t MOBILE_ROUTE_SWITCH_HYSTERESIS = 8;
constexpr uint8_t MOBILE_ROUTE_MAX_HOP = 15;
constexpr uint16_t MOBILE_ROUTE_MAX_COST = 4095;
constexpr uint8_t MOBILE_ROUTE_SHELL_UNKNOWN = 0xff;
constexpr int8_t MOBILE_ROUTE_RSSI_MIN = -100;
constexpr int8_t MOBILE_ROUTE_RSSI_MAX = -30;
constexpr uint8_t MOBILE_ROUTE_HOP_COST = 4;
constexpr uint8_t MOBILE_ROUTE_LOSS_COST = 2;

#pragma pack(push, 1)
struct MobileRouteAdvertisement {
  uint32_t magic;
  uint8_t version;
  uint8_t size;
  uint8_t hop;
  uint8_t reserved;
  uint16_t conductorId;
  uint16_t senderId;
  uint32_t sessionNonce;
  uint32_t sequence;
  uint16_t freshnessMs;
  uint16_t routeCost;
};
#pragma pack(pop)

static_assert(sizeof(MobileRouteAdvertisement) == MOBILE_ROUTE_SIZE, "Mobile route advertisement wire size changed");
static_assert(sizeof(MobileRouteAdvertisement) != 84, "Mobile route advertisement must remain distinct from NodeMessage");
static_assert(MOBILE_ROUTE_SIZE <= 250, "Mobile route advertisement exceeds ESP-NOW payload capacity");

constexpr uint8_t nextMobileRouteHop(uint8_t hop) {
  return hop < MOBILE_ROUTE_MAX_HOP ? static_cast<uint8_t>(hop + 1U) : MOBILE_ROUTE_MAX_HOP;
}

constexpr uint16_t addMobileRouteCost(uint16_t cost, uint16_t addition) {
  return cost >= MOBILE_ROUTE_MAX_COST || addition >= MOBILE_ROUTE_MAX_COST - cost
    ? MOBILE_ROUTE_MAX_COST : static_cast<uint16_t>(cost + addition);
}

inline MobileRouteAdvertisement makeMobileRouteAdvertisement(uint16_t conductorId, uint16_t senderId,
    uint32_t sessionNonce, uint32_t sequence, uint8_t hop, uint16_t routeCost) {
  MobileRouteAdvertisement advertisement = {};
  advertisement.magic = MOBILE_ROUTE_MAGIC;
  advertisement.version = MOBILE_ROUTE_VERSION;
  advertisement.size = MOBILE_ROUTE_SIZE;
  advertisement.hop = hop;
  advertisement.conductorId = conductorId;
  advertisement.senderId = senderId;
  advertisement.sessionNonce = sessionNonce;
  advertisement.sequence = sequence;
  advertisement.freshnessMs = MOBILE_ROUTE_FRESHNESS_MS;
  advertisement.routeCost = routeCost;
  return advertisement;
}

inline bool isMobileRouteAdvertisement(const MobileRouteAdvertisement &advertisement) {
  return advertisement.magic == MOBILE_ROUTE_MAGIC
    && advertisement.version == MOBILE_ROUTE_VERSION
    && advertisement.size == MOBILE_ROUTE_SIZE
    && advertisement.reserved == 0
    && advertisement.conductorId != 0
    && advertisement.senderId != 0
    && advertisement.freshnessMs == MOBILE_ROUTE_FRESHNESS_MS
    && advertisement.hop <= MOBILE_ROUTE_MAX_HOP
    && advertisement.routeCost <= MOBILE_ROUTE_MAX_COST;
}

inline bool mobileRouteSequenceNewer(uint32_t candidate, uint32_t previous) {
  return static_cast<int32_t>(candidate - previous) > 0;
}

class MobileRouteModel {
 public:
  // Selects a parent from receiver-observed RSSI and conductor-wide sequence freshness.
  bool observe(const MobileRouteAdvertisement &advertisement, int8_t rssi, uint32_t now) {
    expire(now);
    if (!isMobileRouteAdvertisement(advertisement) || advertisement.hop >= MOBILE_ROUTE_MAX_HOP) return false;
    if (_valid && (advertisement.conductorId != _conductorId || advertisement.sessionNonce != _sessionNonce)) return false;
    if (_haveSequence && advertisement.sequence != _latestSequence
        && !mobileRouteSequenceNewer(advertisement.sequence, _latestSequence)) return false;

    const bool sequenceAdvanced = !_haveSequence || advertisement.sequence != _latestSequence;
    const uint32_t sequenceGap = _haveSequence && sequenceAdvanced
      ? advertisement.sequence - _latestSequence - 1U : 0;
    const uint16_t lossCost = static_cast<uint16_t>((sequenceGap > 8U ? 8U : sequenceGap) * MOBILE_ROUTE_LOSS_COST);
    const uint16_t cost = observedCost(advertisement, rssi, lossCost);
    if (sequenceAdvanced) {
      _latestSequence = advertisement.sequence;
      _haveSequence = true;
    }

    if (!_valid) {
      select(advertisement, cost, now);
      return true;
    }
    if (advertisement.senderId == _parentId) {
      _cost = cost;
      _hop = nextMobileRouteHop(advertisement.hop);
      _lastSeen = now;
      return false;
    }
    if (addMobileRouteCost(cost, MOBILE_ROUTE_SWITCH_HYSTERESIS) >= _cost) {
      clearCandidate();
      return false;
    }
    if (_candidateId != advertisement.senderId) {
      _candidateId = advertisement.senderId;
      _candidateSince = now;
      return false;
    }
    if (now - _candidateSince < MOBILE_ROUTE_MIN_DWELL_MS) return false;
    select(advertisement, cost, now);
    return true;
  }

  void expire(uint32_t now) {
    if (_valid && now - _lastSeen > MOBILE_ROUTE_FRESHNESS_MS) {
      _valid = false;
      _haveSequence = false;
      _hop = MOBILE_ROUTE_SHELL_UNKNOWN;
      _cost = MOBILE_ROUTE_MAX_COST;
      _parentId = 0;
      clearCandidate();
    }
  }

  bool valid(uint32_t now) {
    expire(now);
    return _valid;
  }

  uint8_t shell(uint32_t now) {
    return valid(now) ? _hop : MOBILE_ROUTE_SHELL_UNKNOWN;
  }

  uint16_t parentId() const { return _parentId; }
  uint16_t conductorId() const { return _conductorId; }
  uint32_t sessionNonce() const { return _sessionNonce; }
  uint32_t sequence() const { return _latestSequence; }
  uint16_t cost() const { return _cost; }

 private:
  static uint16_t observedCost(const MobileRouteAdvertisement &advertisement, int8_t rssi, uint16_t lossCost) {
    const int16_t boundedRssi = rssi < MOBILE_ROUTE_RSSI_MIN ? MOBILE_ROUTE_RSSI_MIN
      : rssi > MOBILE_ROUTE_RSSI_MAX ? MOBILE_ROUTE_RSSI_MAX : rssi;
    const uint16_t rssiCost = static_cast<uint16_t>(MOBILE_ROUTE_RSSI_MAX - boundedRssi);
    return addMobileRouteCost(advertisement.routeCost,
      static_cast<uint16_t>(rssiCost + MOBILE_ROUTE_HOP_COST + lossCost));
  }

  void select(const MobileRouteAdvertisement &advertisement, uint16_t cost, uint32_t now) {
    _valid = true;
    _conductorId = advertisement.conductorId;
    _sessionNonce = advertisement.sessionNonce;
    _parentId = advertisement.senderId;
    _hop = nextMobileRouteHop(advertisement.hop);
    _cost = cost;
    _lastSeen = now;
    clearCandidate();
  }

  void clearCandidate() {
    _candidateId = 0;
    _candidateSince = 0;
  }

  bool _valid = false;
  bool _haveSequence = false;
  uint16_t _conductorId = 0;
  uint16_t _parentId = 0;
  uint16_t _candidateId = 0;
  uint32_t _sessionNonce = 0;
  uint32_t _latestSequence = 0;
  uint32_t _lastSeen = 0;
  uint32_t _candidateSince = 0;
  uint16_t _cost = MOBILE_ROUTE_MAX_COST;
  uint8_t _hop = MOBILE_ROUTE_SHELL_UNKNOWN;
};
// AI: end
