#pragma once

#include <Arduino.h>
#include "global_state.h"
#include "espnow_broadcast.h"
#include "legacy_projection.h"
#include "v3_channels.h"
#include "v3_protocol.h"
#include "peer_telemetry.h"

// #define NODE_DEBUGGING
// #define RELAY_DEBUGGING
#define TESTING_NODE_ID 0

typedef struct {
    uint8_t status;
    char message[40];
} NodeInfo;


const char *command_name(CommandId command) {
    switch (command) {
        case COMMAND_STATE:
            return "UPDATE";
        case COMMAND_OPTIONS:
            return "OPTIONS";
        case COMMAND_ACTION:
            return "ACTION";
        case COMMAND_INFO:
            return "INFO";
        case COMMAND_BEATS:
            return "BEATS";
        default:
            return "?COMMAND?";
    }
}

class MessageReceiver {
  public:
    virtual bool onCommand(CommandId command, void *data) = 0;
    virtual bool onV2Message(const NodeMessage& message) = 0;
    virtual bool isValidV2Command(CommandId command, const uint8_t* data) const = 0;
    virtual bool isValidV3Topic(
        uint8_t topic,
        const V3TopicPayload& payload,
        const MeshNodeHeader& transportSender,
        MessageRecipients recipients,
        int8_t rssi
    ) const = 0;
    virtual bool onV3Topic(
        uint8_t topic,
        const V3TopicPayload& payload,
        const MeshNodeHeader& transportSender,
        MessageRecipients recipients,
        int8_t rssi
    ) = 0;
    virtual bool isValidV3Channel(
        uint8_t channel,
        const TubesChannelPayload& payload,
        const MeshNodeHeader& transportSender,
        MessageRecipients recipients
    ) const = 0;
    virtual bool onV3Channel(
        uint8_t channel,
        const TubesChannelPayload& payload,
        const MeshNodeHeader& transportSender,
        MessageRecipients recipients
    ) = 0;
    virtual bool isValidV3ChannelV2(
        uint8_t channel,
        const TubesChannelMessageV2& message,
        const MeshNodeHeader& transportSender,
        MessageRecipients recipients
    ) const = 0;
    virtual bool onV3ChannelV2(
        uint8_t channel,
        const TubesChannelMessageV2& message,
        const MeshNodeHeader& transportSender,
        MessageRecipients recipients
    ) = 0;
    virtual void onV2PacketObserved(const NodeMessage& message) = 0;
    virtual bool onButton(uint8_t button_id) = 0;
};

class LightNode {
  public:
    static LightNode* instance;

    MessageReceiver *receiver;
    MeshNodeHeader header;
    int8_t lastRssi = 0;
    PeerTelemetry peerTelemetry;

    typedef enum{
        NODE_STATUS_QUIET=0,
        NODE_STATUS_RECEIVING,
        NODE_STATUS_STARTED,
        NODE_STATUS_MAX,
    } NodeStatus;
    NodeStatus status = NODE_STATUS_QUIET;

    PGM_P status_code() const {
        switch (status) {
        case NODE_STATUS_QUIET:
            return PSTR(" (quiet)");
        case NODE_STATUS_RECEIVING:
            return PSTR(" (receiving)");
        case NODE_STATUS_STARTED:
            return PSTR(" (started)");
        default:
            return PSTR("??");
        }
    }

    char node_name[20];

    LightNode(MessageReceiver *r) : receiver(r) {
        instance = this;
    }

    void setWledNetworkOwnership(bool enabled) {
        wledOwnsNetwork = enabled;
    }

    // AI: below section was generated by an AI
    // A received serial character proves that a host is listening more reliably
    // than the external USB-UART bridge's reset-oriented modem-control signals.
    void renewSerialTrace() {
        bool wasEnabled = serialTraceEnabled();
        serialTraceExpiresAt = millis() + SERIAL_TRACE_LEASE_MS;
        if (!wasEnabled)
            Serial.println();
    }

    bool serialTraceEnabled() const {
        return serialTraceExpiresAt != 0
            && int32_t(serialTraceExpiresAt - millis()) > 0;
    }
    // AI: end

  protected:

    bool wledOwnsNetwork = false;
    // AI: below section was generated by an AI
    static constexpr uint32_t SERIAL_TRACE_LEASE_MS = 60000;
    uint32_t serialTraceExpiresAt = 0;
    // AI: end

    const uint32_t STATUS_TIMEOUT_BASE =  3000;    // Base time to wait to send broadcasts
    const uint32_t UPLINK_TIMEOUT      = 20000;    // Time at which uplink is presumed lost
    const uint32_t REBROADCAST_TIME    = 30000;    // Time at which followers are presumed re-uplinked

    TubesTimer statusTimer;      // Use this timer to initialize and check wifi status
    TubesTimer uplinkTimer;      // When this timer ends, assume uplink is lost.
    TubesTimer rebroadcastTimer; // Until this timer ends, re-broadcast messages from uplink

    void onMeshChange() {
        sprintf(node_name,
            "Tube %04X:%04X",
            header.id,
            header.uplinkId
        );

        configureAP();
    }

    void configureAP() {
        // Home lights need the mesh, but their normal WLED network remains authoritative.
        if (wledOwnsNetwork)
            return;

#ifdef DEFAULT_WIFI
        strcpy(multiWiFi[0].clientSSID, DEFAULT_WIFI);
        strcpy(multiWiFi[0].clientPass, DEFAULT_WIFI_PASSWORD);
#else
        // Don't connect to any networks.
        strcpy(multiWiFi[0].clientSSID, "");
        strcpy(multiWiFi[0].clientPass, "");
#endif

        // By default, we don't want these visible.
        apBehavior = AP_BEHAVIOR_BUTTON_ONLY; // Must press button for 6 seconds to get AP
    }

    void onPeerPing(const MeshNodeHeader& node) {
        // When receiving a message, if the IDs match, it's a conflict
        // Reset to create a new ID.
        if (node.id == header.id) {
            Serial.println("Detected an ID conflict.");
            reset();
            return;
        }

        if (node.id > header.uplinkId && node.id > header.id) {
#ifdef RELAY_DEBUGGING
          // When debugging relay, pretend not to see any nodes above 0x800
          if (node->id < 0x800)
#endif
            follow(&node);
        }

        // If the message arrived from our uplink, track that we're still linked.
        if (node.id == header.uplinkId) {
            uplinkTimer.start(UPLINK_TIMEOUT);
        }

        // If a message indicates that another node is following this one, or
        // should be (it's not following anything, but this node's ID is higher)
        // enter or continue re-broadcasting mode.
        if (shouldRenewRelayDuty(header, node)) {
            if (!isLeading()) {
                Serial.printf("     LEADING because %04X/%04X is following me\n", node.id, node.uplinkId);
            }
            rebroadcastTimer.start(REBROADCAST_TIME);
        }
    }

    // AI: below section was generated by an AI
    MeshNodeHeader nativeHeader() const {
        MeshNodeHeader native = header;
        native.version = TUBES_PROTOCOL_V3;
        return native;
    }

    MeshNodeHeader legacyHeader() const {
        MeshNodeHeader legacy = header;
        legacy.version = TUBES_PROTOCOL_V2;
        return legacy;
    }
    // AI: end

    void printMessage(const NodeMessage* message, signed int rssi) const {
        Serial.printf("%04X/%04X v%d ",
            message->header.id,
            message->header.uplinkId,
            message->header.version
        );
        if (message->header.version == TUBES_PROTOCOL_V3)
            Serial.printf("TOPIC-%02X", message->command);
        else
            Serial.print(command_name(message->command));
        if (message->header.version == TUBES_PROTOCOL_V3 && isKnownTubesChannel(message->command)) {
            const TubesChannelPayload& payload = *reinterpret_cast<const TubesChannelPayload*>(message->data);
            Serial.printf("[%04X/%04X k%u s%u]",
                payload.envelope.channelId,
                payload.envelope.sourceControlId,
                payload.envelope.messageKind,
                payload.envelope.sequence
            );
        }
        if (message->recipients == RECIPIENTS_ROOT)
            Serial.printf(":ROOT");
        if (rssi)
            Serial.printf(" %ddB ", rssi);
    }

    // AI: below section was generated by an AI
    void onPeerData(const uint8_t* address, const NodeMessage* message, uint8_t len, signed int rssi, bool broadcast) {
        (void)address;
        (void)len;
        (void)broadcast;

        bool legacyPacket = message->header.version == TUBES_PROTOCOL_V2;
        V3ProjectionTrailer projectionTrailer;
        bool legacyProjection = legacyPacket
            && readV3ProjectionTrailer(*message, projectionTrailer);
        if (legacyPacket) {
            if (!receiver->isValidV2Command(message->command, message->data))
                return;
            receiver->onV2PacketObserved(*message);
            // Legacy devices remain visible to Surveyor without joining native v3 topology.
            peerTelemetry.observe(message->header.id, message->header.uplinkId,
                LEGACY_PROTOCOL_GENERATION, static_cast<int8_t>(rssi), millis());
        } else if (isKnownTubesChannel(message->command)) {
            const TubesChannelPayload& payload = *reinterpret_cast<const TubesChannelPayload*>(message->data);
            if (!receiver->isValidV3Channel(
                    message->command,
                    payload,
                    message->header,
                    message->recipients))
                return;
        } else if (isKnownV3Topic(message->command)) {
            const V3TopicPayload& payload = *reinterpret_cast<const V3TopicPayload*>(message->data);
            if (!receiver->isValidV3Topic(
                    message->command,
                    payload,
                    message->header,
                    message->recipients,
                    rssi))
                return;
        }

        uint8_t incomingGeneration = protocolGenerationFromId(message->header.id);

        // Unknown future v3 topics may pass through an established route, but they
        // cannot change this firmware's topology or radio diagnostics.
        bool compatibleGenerationPacket = !legacyPacket
            && incomingGeneration >= CURRENT_PROTOCOL_GENERATION;
        if (compatibleGenerationPacket
            && (isKnownTubesChannel(message->command)
                || isKnownV3Topic(message->command))) {
            lastRssi = rssi;
            onPeerPing(message->header);
            peerTelemetry.observe(message->header.id, message->header.uplinkId,
                incomingGeneration, static_cast<int8_t>(rssi), millis());
        } else if (legacyPacket) {
            // V2 nodes never participate in native V3 Control election. They can still
            // make this V3 node relay for them through its translated legacy identity.
            MeshNodeHeader translated = legacyHeader();
            if (shouldRenewRelayDuty(translated, message->header))
                rebroadcastTimer.start(REBROADCAST_TIME);
        }

        MeshNodeHeader routeHeader = legacyPacket ? legacyHeader() : nativeHeader();
        MeshRoutePlan route = planMeshRoute(routeHeader, isFollowing(), isLeading(), *message);
        if (!route.accepted) {
#ifdef NODE_DEBUGGING
            Serial.print("  -- ignored ");
            printMessage(message, rssi);
            Serial.println();
#endif
            return;
        }

        // Apply only at the root on the upward trip, then at every follower on the declaration trip.
        if (route.applyLocally) {
            bool traceMessage = serialTraceEnabled();
            if (traceMessage) {
                Serial.print("  >> ");
                printMessage(message, rssi);
                Serial.print(" ");
            }

            bool valid;
            if (message->header.version == TUBES_PROTOCOL_V3 && isKnownTubesChannel(message->command)) {
                const TubesChannelPayload& payload = *reinterpret_cast<const TubesChannelPayload*>(message->data);
                valid = receiver->onV3Channel(
                    message->command,
                    payload,
                    message->header,
                    message->recipients
                );
            } else if (message->header.version == TUBES_PROTOCOL_V3) {
                const V3TopicPayload& payload = *reinterpret_cast<const V3TopicPayload*>(message->data);
                valid = receiver->onV3Topic(
                    message->command,
                    payload,
                    message->header,
                    message->recipients,
                    rssi
                );
                // Unknown downward topics remain relayable so an older v3 relay does
                // not partition newer topic implementations from their followers.
                if (!valid && !isKnownV3Topic(message->command) && message->recipients == RECIPIENTS_ALL)
                    valid = true;
            } else
                valid = receiver->onV2Message(*message);
            if (traceMessage)
                Serial.println();

            if (!valid)
                return;

            // Clock synchronization follows successful application validation, so stale
            // authority packets and unknown topics cannot move the visual timebase.
            // A gen0 projection is carried for legacy descendants only; native
            // declarations remain the complete timing authority for gen1 receivers.
            if (route.synchronizeClock
                && (message->header.version == TUBES_PROTOCOL_V2
                    || isKnownTubesChannel(message->command)
                    || isKnownV3Topic(message->command))
                && !legacyProjection) {
                uint32_t new_timebase = message->timebase - millis() + 3; // Factor for network delay
                int32_t diff = new_timebase - strip.timebase;
                if (diff < -10 || diff > 10)
                    strip.timebase = new_timebase;
            }
        }

        // Preserve the accepted packet while advancing it one hop through the tree.
        if (route.relay) {
            NodeMessage msg = makeRelayedMessage(routeHeader, isFollowing(), *message);
            if (!isFollowing()
                && msg.header.version == TUBES_PROTOCOL_V3
                && isKnownTubesChannel(msg.command)
                && msg.recipients == RECIPIENTS_ALL) {
                TubesChannelPayload& payload = *reinterpret_cast<TubesChannelPayload*>(msg.data);
                if (payload.envelope.messageKind == ChannelRequest)
                    payload.envelope.messageKind = ChannelDeclaration;
            }
#ifdef NODE_DEBUGGING
            Serial.println("rebroadcast");
#endif
            broadcastMessage(&msg, true);
        }
    }

    // Validate, apply, and relay one variable-length generation-1 channel snapshot.
    // The Wi-Fi-task prefix filter has already rejected malformed lengths and framing.
    void onPeerChannelV2(
        const uint8_t* address,
        const TubesChannelMessageV2* message,
        uint8_t len,
        signed int rssi,
        bool broadcast
    ) {
        (void)address;
        (void)broadcast;
        if (!receiver->isValidV3ChannelV2(
                message->command,
                *message,
                message->header,
                message->recipients))
            return;

        lastRssi = rssi;
        onPeerPing(message->header);
        peerTelemetry.observe(message->header.id, message->header.uplinkId,
            protocolGenerationFromId(message->header.id), static_cast<int8_t>(rssi), millis());

        NodeMessage routeMessage;
        routeMessage.header = message->header;
        routeMessage.recipients = message->recipients;
        routeMessage.command = message->command;
        MeshNodeHeader routeHeader = nativeHeader();
        MeshRoutePlan route = planMeshRoute(
            routeHeader, isFollowing(), isLeading(), routeMessage);
        if (!route.accepted)
            return;

        if (route.applyLocally) {
            if (serialTraceEnabled()) {
                Serial.printf(
                    "  >> %04X/%04X v3 CHANNEL2-%02X[%04X/%04X k%u s%u] %ddB %uB ",
                    message->header.id,
                    message->header.uplinkId,
                    message->command,
                    message->envelope.channelId,
                    message->envelope.sourceControlId,
                    message->envelope.messageKind,
                    message->envelope.sequence,
                    rssi,
                    len
                );
            }
            if (!receiver->onV3ChannelV2(
                    message->command,
                    *message,
                    message->header,
                    message->recipients))
                return;
            if (serialTraceEnabled())
                Serial.println();
            if (route.synchronizeClock) {
                uint32_t newTimebase = message->timebase - millis() + 3;
                int32_t difference = newTimebase - strip.timebase;
                if (difference < -10 || difference > 10)
                    strip.timebase = newTimebase;
            }
        }

        if (route.relay) {
            TubesChannelMessageV2 relayed;
            memcpy(&relayed, message, len);
            relayed.header = routeHeader;
            if (!isFollowing()) {
                relayed.recipients = RECIPIENTS_ALL;
                relayed.envelope.messageKind = ChannelDeclaration;
            }
            relayed.timebase = strip.timebase + millis();
            if (isValidChannelMessageV2Prefix(
                    reinterpret_cast<const uint8_t*>(&relayed), len))
                espnowBroadcast.send(reinterpret_cast<const uint8_t*>(&relayed), len);
        }
    }
    // AI: end

    void broadcastMessage(NodeMessage *message, bool is_rebroadcast=false) {
        // Don't broadcast anything if this node isn't active.
        if (status != NODE_STATUS_STARTED) {
            if (status == NODE_STATUS_RECEIVING && statusTimer.ended()) {
                status = NODE_STATUS_STARTED;
                statusTimer.stop();
                Serial.printf("LightNode %s\n", status_code());
            } else {
                Serial.printf("broadcastMessage() - not started - %s\n", status_code());
                return;
            }
        }
        message->timebase = strip.timebase + millis();

#ifdef NODE_DEBUGGING
        Serial.print("  <<< ");
        printMessage(message, 0);
        Serial.println();
#endif

        __attribute__((unused)) auto success = espnowBroadcast.send((const uint8_t*)message, sizeof(*message));
#ifdef NODE_DEBUGGING
        if (!success) {
            Serial.println("espnowBroadcast.send() failed!");
        } else {
            Serial.println("successful broadcast");
        }
#endif

    }

  public:

    void sendCommand(
        CommandId command,
        const void *data,
        uint8_t len,
        const V3ProjectionTrailer* projectionTrailer = nullptr
    ) {
        // if (!ESP_NOW.isStarted()) {
        //     Serial.println("SendCommand ESP Not Started!");
        //     return;
        // }
        if (len > MESSAGE_DATA_SIZE) {
            Serial.printf("Message is too big: %d vs %d\n",
                len, MESSAGE_DATA_SIZE);
            return;
        }
        if (projectionTrailer && len > V3_PROJECTION_TRAILER_OFFSET) {
            Serial.printf("Legacy command overlaps projection trailer: %d\n", len);
            return;
        }

        NodeMessage message;
        message.header = legacyHeader();
        if (command == COMMAND_INFO) {
            message.recipients = RECIPIENTS_NEIGHBORS;
        } else if (command == COMMAND_STATE) {
            message.recipients = RECIPIENTS_ALL;
        } else if (isFollowing()) {
            // Follower nodes must request that the root re-sends this message
            message.recipients = RECIPIENTS_ROOT;
        } else {
            message.recipients = RECIPIENTS_ALL;
        }
        message.command = command;
        if (len > 0)
            memcpy(&message.data, data, len);
        if (projectionTrailer)
            writeV3ProjectionTrailer(message, *projectionTrailer);
#ifdef NODE_DEBUGGING
        Serial.println("sendCommand");
#endif
        broadcastMessage(&message);
    }

    // AI: below section was generated by an AI
    // Send one validated v3 topic through the same root-oriented routing tree as v2.
    bool sendV3Topic(uint8_t topic, const V3TopicPayload& payload) {
        if (!isValidV3TopicPayload(topic, payload)) {
            Serial.printf("Invalid v3 topic payload: %02X\n", topic);
            return false;
        }

        NodeMessage message;
        message.header = nativeHeader();
        bool neighborsOnly = topic == V3TopicPresence
            || (topic == V3TopicPosition && payload.envelope.messageKind == V3Advertisement);
        if (neighborsOnly)
            message.recipients = RECIPIENTS_NEIGHBORS;
        else if (isFollowing())
            message.recipients = RECIPIENTS_ROOT;
        else
            message.recipients = RECIPIENTS_ALL;
        message.command = topic;
        memcpy(message.data, &payload, sizeof(payload));
        broadcastMessage(&message);
        return true;
    }

    // Send one channel packet over the shared Control tree.
    bool sendV3Channel(uint8_t channel, const TubesChannelPayload& payload) {
        if (!isValidTubesChannelPayload(channel, payload)) {
            Serial.printf("Invalid v3 channel payload: %02X\n", channel);
            return false;
        }

        NodeMessage message;
        message.header = nativeHeader();
        if (payload.envelope.messageKind == ControlBeacon)
            message.recipients = RECIPIENTS_NEIGHBORS;
        else if (payload.envelope.messageKind == ChannelDeclaration)
            message.recipients = RECIPIENTS_ALL;
        else if (isFollowing())
            message.recipients = RECIPIENTS_ROOT;
        else
            return false;
        message.command = channel;
        memcpy(message.data, &payload, sizeof(payload));
        broadcastMessage(&message);
        return true;
    }

    // Carry one already-validated native channel packet directly to nearby peers.
    bool sendV3NeighborChannel(uint8_t channel, const TubesChannelPayload& payload) {
        if (!isValidTubesChannelPayload(channel, payload)) {
            Serial.printf("Invalid v3 neighbor channel payload: %02X\n", channel);
            return false;
        }
        NodeMessage message;
        message.header = nativeHeader();
        message.recipients = RECIPIENTS_NEIGHBORS;
        message.command = channel;
        memcpy(message.data, &payload, sizeof(payload));
        broadcastMessage(&message);
        return true;
    }

    // Send one variable-length channel snapshot after the complete packet has
    // passed the same ingress validation used by receivers.
    bool sendV3ChannelV2(uint8_t channel, TubesChannelMessageV2& message) {
        message.header = nativeHeader();
        message.command = channel;
        if (message.envelope.messageKind == ChannelDeclaration) {
            if (isFollowing())
                return false;
            message.recipients = RECIPIENTS_ALL;
        } else if (message.envelope.messageKind == ChannelRequest && isFollowing()) {
            message.recipients = RECIPIENTS_ROOT;
        } else {
            return false;
        }
        message.timebase = strip.timebase + millis();
        size_t length = channelMessageV2WireSize(message.envelope.bodyLength);
        if (!isValidChannelMessageV2Prefix(
                reinterpret_cast<const uint8_t*>(&message), length)) {
            Serial.printf("Invalid variable v3 channel: %02X\n", channel);
            return false;
        }
        return espnowBroadcast.send(reinterpret_cast<const uint8_t*>(&message), length);
    }
    // AI: end

    void setup() {
#ifdef NODE_DEBUGGING
        reset(TESTING_NODE_ID);
#else
        reset();
#endif


#ifdef NODE_DEBUGGING
        delay(2000);
#endif

        espnowBroadcast.registerFilter(onEspNowFilter);
        espnowBroadcast.registerCallback(onEspNowMessage);

        Serial.println("setup: ok");
    }

    void update() {

        //process any wifi events to turn on/off ESPNode
        updateESPNowState();

        // Check the last time we heard from the uplink node
        if (isFollowing() && uplinkTimer.ended()) {
            follow(NULL);
        }
    }

    void reset(DeviceId id = 0) {
        ProtocolLocalValue localValue = protocolLocalValueFromId(id);
        if (localValue == 0) {
#if defined(LOLIN_WIFI_FIX) && (defined(ARDUINO_ARCH_ESP32C3) || defined(ARDUINO_ARCH_ESP32S2) || defined(ARDUINO_ARCH_ESP32S3))
            localValue = random(10, 255);  // Leave room at bottom and top of 12 bits
#else
            localValue = random(256, 4000);  // Leave room at bottom and top of 12 bits
#endif
        }
        header.id = makeDeviceId(CURRENT_PROTOCOL_GENERATION, localValue);
        follow(NULL);
    }

    void follow(const MeshNodeHeader* node) {
        if (node == NULL) {
            if (header.uplinkId != 0) {
                Serial.println("Uplink lost");
            }

            // Unfollow: following zero means you have no uplink
            header.uplinkId = 0;
            onMeshChange();
            return;
        }

        // Already following? ignore
        if (header.uplinkId == node->id)
            return;

        // Follow
        Serial.printf("Following %04X:%04X\n",
            node->id,
            node->uplinkId
        );
        header.uplinkId = node->id;
        onMeshChange();
    }

    bool isFollowing() const {
        return header.uplinkId != 0;
    }
    bool isLeading() const {
        // For now, leading mode is defined as being in re-broadcast mode for any reason.
        // Any node that thinks it has the highest ID is leading, but so are any nodes that
        // have seen another node that should be following the leader it is following.
        return !rebroadcastTimer.ended();
    }

protected:

    void updateESPNowState() {
        auto state = espnowBroadcast.getState();
        static auto prev = espnowBroadcast.STOPPED;
        switch(state) {
            case ESPNOWBroadcast::STOPPED:
                if (NODE_STATUS_QUIET != status) {
                    Serial.printf("updateESPNowState() - %d node_status:%s\n", state, status_code());
                    status = NODE_STATUS_QUIET;
                    rebroadcastTimer.stop();
                    Serial.printf("LightNode %s\n", status_code());
                }
                break;
            case ESPNOWBroadcast::STARTING: {}
                if ( state != prev ) {
                    Serial.printf("updateESPNowState() - %d node_status:%s\n", state, status_code());
                }
                break;
            case ESPNOWBroadcast::STARTED:
                if (NODE_STATUS_QUIET == status) {
                    Serial.printf("updateESPNowState() - %d node_status:%s\n", state, status_code());
                    status = NODE_STATUS_RECEIVING;
                    statusTimer.start(STATUS_TIMEOUT_BASE - protocolLocalValueFromId(header.id) / 2);
                    Serial.printf("LightNode %s\n", status_code());
                }
                break;
            default:
                break;
        }
        prev = state;
    }

    typedef struct wizmote_message {
        uint8_t program;      // 0x91 for ON button, 0x81 for all others
        uint8_t seq[4];       // Incremetal sequence number 32 bit unsigned integer LSB first
        uint8_t byte5 = 32;   // Unknown
        uint8_t button;       // Identifies which button is being pressed
        uint8_t byte8 = 1;    // Unknown, but always 0x01
        uint8_t byte9 = 100;  // Unnkown, but always 0x64

        uint8_t byte10;  // Unknown, maybe checksum
        uint8_t byte11;  // Unknown, maybe checksum
        uint8_t byte12;  // Unknown, maybe checksum
        uint8_t byte13;  // Unknown, maybe checksum
    } wizmote_message;

    void onWizmote(const uint8_t* address, const wizmote_message* data, uint8_t len) {
        static uint32_t last_seq = 0;
        uint32_t cur_seq = data->seq[0] | (data->seq[1] << 8) | (data->seq[2] << 16) | (data->seq[3] << 24);
        if (cur_seq == last_seq)
            return;
        last_seq = cur_seq;

        receiver->onButton(data->button);
    }

    static void onEspNowMessage(const uint8_t *address, const uint8_t *msg, uint8_t len, int8_t rssi) {
        // basic length and field checking has been done in onEspNowFilter
        if (msg) {
            if(len == sizeof(NodeMessage)) {
                instance->onPeerData(address, (const NodeMessage*)msg, len, rssi, true);
            } else if (isValidChannelMessageV2Prefix(msg, len)) {
                instance->onPeerChannelV2(
                    address,
                    reinterpret_cast<const TubesChannelMessageV2*>(msg),
                    len,
                    rssi,
                    true
                );
            } else if(len == sizeof(wizmote_message)) {
                instance->onWizmote(address, (const wizmote_message*)msg, len);
            } else {
#ifdef NODE_DEBUGGING
                Serial.printf("wrong size EspNowMessage received %d\n", len);
#endif
            }
        }
    }

    static bool onEspNowFilter(const uint8_t *address, const uint8_t *msg, uint8_t len, int8_t rssi) {
        (void)address;
        (void)rssi;
        if (isValidChannelMessageV2Prefix(msg, len))
            return true;
        if (len == sizeof(NodeMessage)) {
            const NodeMessage& message = *reinterpret_cast<const NodeMessage*>(msg);
            if (message.recipients != RECIPIENTS_ALL
                && message.recipients != RECIPIENTS_ROOT
                && message.recipients != RECIPIENTS_NEIGHBORS)
                return false;
            if (message.header.version == TUBES_PROTOCOL_V2)
                return true;
            if (message.header.version != TUBES_PROTOCOL_V3)
                return false;
            if (isKnownTubesChannel(message.command)) {
                const TubesChannelPayload& payload = *reinterpret_cast<const TubesChannelPayload*>(message.data);
                return isValidTubesChannelPayload(message.command, payload);
            }
            const V3TopicPayload& payload = *reinterpret_cast<const V3TopicPayload*>(message.data);
            return isValidV3TopicPayload(message.command, payload);
        } else if (len == sizeof(wizmote_message)) {
            auto wizmote = (const wizmote_message*)msg;
            return !( wizmote->byte8 != 1 || wizmote->byte9 != 100 || wizmote->byte5 != 32);
        }
        return false;
    }
};

LightNode* LightNode::instance = nullptr;
