#pragma once

#include <stddef.h>
#include <stdint.h>

// AI: below section was generated by an AI
// Maintains a bounded, allocation-free view of recently heard Tubes peers for field diagnostics.
constexpr size_t TUBES_PEER_TELEMETRY_CAPACITY = 24;

struct PeerTelemetryEntry {
  uint16_t nodeId = 0;
  uint16_t uplinkId = 0;
  uint32_t lastSeenMs = 0;
  uint32_t samples = 0;
  int16_t smoothedRssi = 0;
  int8_t latestRssi = 0;
  int8_t minimumRssi = 0;
  int8_t maximumRssi = 0;
};

// Trust model: display-integrity only. Mesh frames are unauthenticated and the
// 24-entry LRU is evictable by forged ids; the control plane stays denied.
class PeerTelemetry {
public:
  void observe(uint16_t nodeId, uint16_t uplinkId, int8_t rssi, uint32_t now) {
    // nodeId 0 is the unset sentinel; never record it.
    if (nodeId == 0) return;

    PeerTelemetryEntry *entry = find(nodeId);
    if (entry == nullptr) entry = allocate(now);
    if (entry == nullptr) return;

    if (entry->nodeId != nodeId) *entry = PeerTelemetryEntry{};
    entry->nodeId = nodeId;
    entry->uplinkId = uplinkId;
    entry->lastSeenMs = now;
    entry->latestRssi = rssi;

    if (entry->samples == 0) {
      entry->minimumRssi = rssi;
      entry->maximumRssi = rssi;
      entry->smoothedRssi = rssi;
    } else {
      if (rssi < entry->minimumRssi) entry->minimumRssi = rssi;
      if (rssi > entry->maximumRssi) entry->maximumRssi = rssi;
      entry->smoothedRssi = static_cast<int16_t>((entry->smoothedRssi * 3 + rssi) / 4);
    }
    if (entry->samples != UINT32_MAX) entry->samples++;
  }

  size_t count() const {
    size_t used = 0;
    for (const PeerTelemetryEntry &entry : _entries) {
      if (entry.nodeId != 0) used++;
    }
    return used;
  }

  const PeerTelemetryEntry *entry(size_t index) const {
    size_t used = 0;
    for (const PeerTelemetryEntry &candidate : _entries) {
      if (candidate.nodeId == 0) continue;
      if (used++ == index) return &candidate;
    }
    return nullptr;
  }

  const PeerTelemetryEntry *get(uint16_t nodeId) const {
    for (const PeerTelemetryEntry &entry : _entries) {
      if (entry.nodeId == nodeId) return &entry;
    }
    return nullptr;
  }

private:
  PeerTelemetryEntry *find(uint16_t nodeId) {
    for (PeerTelemetryEntry &entry : _entries) {
      if (entry.nodeId == nodeId) return &entry;
    }
    return nullptr;
  }

  PeerTelemetryEntry *allocate(uint32_t now) {
    PeerTelemetryEntry *oldest = &_entries[0];
    uint32_t oldestAge = 0;
    for (PeerTelemetryEntry &entry : _entries) {
      if (entry.nodeId == 0) return &entry;
      const uint32_t age = now - entry.lastSeenMs;
      if (age >= oldestAge) {
        oldest = &entry;
        oldestAge = age;
      }
    }
    return oldest;
  }

  PeerTelemetryEntry _entries[TUBES_PEER_TELEMETRY_CAPACITY] = {};
};
// AI: end
