#pragma once

#include <stddef.h>
#include <stdint.h>

#include "device_report_protocol.h"

// AI: below section was generated by an AI
struct RunningImageInfo {
  uint32_t partitionAddress = 0;
  uint32_t partitionSizeBytes = 0;
  uint32_t imageLengthBytes = 0;
  uint32_t releaseHash = 0;
  uint8_t hardwareFamily = TubeHardwareUnknown;
  uint8_t firmwareVariant = TubeVariantStandard;
  uint8_t imageSha256[32] = {0};
};

inline bool runningImageRangeIsValid(size_t imageLength, size_t offset, size_t length) {
  return imageLength > 0
      && length > 0
      && offset < imageLength
      && length <= imageLength - offset;
}

#if defined(ARDUINO_ARCH_ESP32)
bool inspectRunningImage(RunningImageInfo& info, char* error, size_t errorLength);
bool readRunningImageChunk(
    const RunningImageInfo& info,
    size_t offset,
    uint8_t* destination,
    size_t length,
    char* error,
    size_t errorLength
);
#endif
// AI: end
