#pragma once

#include <stddef.h>
#include <stdint.h>

#include "device_report_protocol.h"
#include "firmware_image_source.h"

// AI: below section was generated by an AI
struct RunningImageInfo {
  uint32_t partitionAddress = 0;
  uint32_t partitionSizeBytes = 0;
  uint32_t imageLengthBytes = 0;
  uint32_t releaseHash = 0;
  uint8_t hardwareFamily = TubeHardwareUnknown;
  uint8_t firmwareVariant = TubeVariantStandard;
  uint8_t imageMd5[16] = {0};
  uint8_t imageSha256[32] = {0};
};

inline bool runningImageRangeIsValid(size_t imageLength, size_t offset, size_t length) {
  return firmwareImageRangeIsValid(imageLength, offset, length);
}

#if defined(ARDUINO_ARCH_ESP32)
bool inspectRunningImage(RunningImageInfo& info, char* error, size_t errorLength);
bool readRunningImageChunk(
    const RunningImageInfo& info,
    size_t offset,
    uint8_t* destination,
    size_t length,
    char* error,
    size_t errorLength
);

// Adapts the verified running application partition to the same source
// contract used by stored carrier artifacts. The supplied target describes
// the running artifact; carrier hardware is intentionally not inferred here.
class RunningFirmwareImageSource : public FirmwareImageSource {
public:
  explicit RunningFirmwareImageSource(const FirmwareTargetContract& artifactTarget)
      : _artifactTarget(artifactTarget) {}

  bool inspect(FirmwareImageArtifact& artifact) override;
  bool read(size_t offset, uint8_t* destination, size_t length) override;

private:
  FirmwareTargetContract _artifactTarget;
  RunningImageInfo _runningInfo;
  FirmwareImageArtifact _artifact;
  bool _inspected = false;
};
#endif
// AI: end
