#pragma once

#include <stddef.h>
#include <stdint.h>

// AI: below section was generated by an AI
constexpr size_t TUBES_S3_PREVIEW_PIXELS = 12;

struct TubesS3FieldStatus {
  bool isMaster = false;
  bool powerSave = false;
  uint8_t role = 0;
  uint8_t patternId = 0;
  uint8_t paletteId = 0;
  uint16_t bpm = 0;
  uint8_t beat = 0;
  size_t peerCount = 0;
  uint32_t preview[TUBES_S3_PREVIEW_PIXELS] = {};
};

struct TubesS3PeerStatus {
  uint16_t nodeId = 0;
  uint16_t uplinkId = 0;
  uint32_t lastSeenMs = 0;
  uint32_t samples = 0;
  int8_t latestRssi = 0;
  int8_t minimumRssi = 0;
  int8_t maximumRssi = 0;
};

bool tubesS3ReadStatus(TubesS3FieldStatus &status);
bool tubesS3ReadPeer(size_t index, TubesS3PeerStatus &peer);
bool tubesS3ForceNext();
bool tubesS3SetMasterAuthority(bool enabled);
// AI: end
