#pragma once

#include <stddef.h>
#include <stdint.h>

// AI: below section was generated by an AI
constexpr size_t TUBES_S3_PREVIEW_PIXELS = 60;
constexpr size_t TUBES_S3_PATTERN_NAME_LENGTH = 24;

struct TubesS3FieldStatus {
  uint16_t deviceId = 0;
  uint16_t tubesVersion = 0;
  uint8_t priority = 0;
  bool isMaster = false;
  bool isFollowing = false;
  bool radioReady = false;
  bool powerSave = false;
  uint8_t role = 0;
  uint8_t radioChannel = 0;
  uint8_t patternId = 0;
  uint8_t paletteId = 0;
  uint16_t bpm = 0;
  uint8_t beat = 0;
  size_t peerCount = 0;
  uint16_t uplinkId = 0;
  uint16_t syncSourceId = 0;
  uint32_t receivedPacketCount = 0;
  uint32_t lastPacketMs = 0;
  uint32_t synchronizedPacketCount = 0;
  uint32_t lastSyncMs = 0;
  uint32_t transmittedPacketCount = 0;
  uint32_t lastTransmitMs = 0;
  char patternName[TUBES_S3_PATTERN_NAME_LENGTH] = {};
  uint32_t preview[TUBES_S3_PREVIEW_PIXELS] = {};
};

struct TubesS3PeerStatus {
  uint16_t nodeId = 0;
  uint16_t uplinkId = 0;
  uint32_t lastSeenMs = 0;
  uint32_t samples = 0;
  int8_t latestRssi = 0;
  int8_t minimumRssi = 0;
  int8_t maximumRssi = 0;
};

struct TubesS3RouteStatus {
  bool anchorEnabled = false;
  bool routeValid = false;
  uint8_t shell = 0xff;
  uint16_t conductorId = 0;
  uint16_t parentId = 0;
  uint16_t routeCost = 0;
  uint32_t sequence = 0;
};

bool tubesS3ReadStatus(TubesS3FieldStatus &status);
bool tubesS3ReadPeer(size_t index, TubesS3PeerStatus &peer);
bool tubesS3ReadRoute(TubesS3RouteStatus &route);
bool tubesS3ForceNext();
bool tubesS3ForcePrevious();
bool tubesS3SetMasterAuthority(bool enabled);
bool tubesS3SetAnchorAuthority(bool enabled);
// AI: end
