#include "Tubes.h"

static TubesUsermod tubes;
REGISTER_USERMOD(tubes);

#ifdef TUBES_ENABLE_HTTP_OTA_VFX
// AI: below section was generated by an AI
extern "C" bool tubesHttpOtaVfxBeforeSuspend() {
  tubes.beginHttpOtaVfx();
  const uint32_t started = millis();
  while (!tubes.httpOtaVfxReadyToSuspend() && millis() - started < 1000U) {
    tubes.serviceHttpOtaVfx();
    delay(1);
  }
  tubes.suspendHttpOtaVfx();
  return true;
}

extern "C" bool tubesHttpOtaVfxOnSuccess() {
  tubes.succeedHttpOtaVfx();
  return true;
}

extern "C" void tubesHttpOtaVfxOnError() {
  tubes.failHttpOtaVfx();
}
// AI: end
#endif
