#pragma once

#include "wled.h"
#include "fastled_compat.h"

#include "util.h"
#include "options.h"

// #define USERADIO

#include "FX.h"

#include "virtual_strip.h"
#include "led_strip.h"
#include "master.h"
#include "s3_field_api.h"

#include "controller.h"
#include "debug.h"

#ifndef PIXEL_COUNTS
#define PIXEL_COUNTS DEFAULT_LED_COUNT
#endif

#ifndef DATA_PINS
#define DATA_PINS DEFAULT_LED_PIN
#endif

#ifndef LED_TYPES
#define LED_TYPES DEFAULT_LED_TYPE
#endif

#ifndef DEFAULT_LED_COLOR_ORDER
#define DEFAULT_LED_COLOR_ORDER COL_ORDER_GRB
#endif

#define MASTER_PIN 25
#define LEGACY_PIN 32  // DigUno Q4


class TubesUsermod : public Usermod {
  private:
    PatternController controller;
    DebugController debug = DebugController(controller);
    Master master = Master(controller);
    bool isLegacy = false;
    bool checkedLedSegments = false;
    bool s3AnchorAuthority = false;
    bool otaSuspended = false;
    TubesExperiment::ExperimentOverlay experimentOverlay;
#ifdef TUBES_ENABLE_SPATIAL_PATTERNS
    TubesExperiment::SpatialMode spatialMode = TubesExperiment::SpatialMode::Off;
#endif

#ifdef TUBES_ENABLE_HTTP_OTA_VFX
    void showOtaAcknowledgement(const CRGB &color) {
      if (experimentOverlay.priority(true, false, TubesExperiment::SpatialMode::Off) != TubesExperiment::OverlayKind::OtaAcknowledgement) return;
      for (uint16_t i = 0; i < strip.getLengthTotal(); i++) strip.setPixelColor(i, color);
      strip.show();
    }
#endif

    void randomize() {
      randomSeed(esp_random());
      random16_set_seed(random(0, 65535));
      random16_add_entropy(esp_random());
    }

    void recoverLedBussesIfNeeded() {
      if (strip.getLengthTotal() > 0 || BusManager::getNumBusses() > 0 || !busConfigs.empty()) return;

#ifdef TUBES_NULL_OUTPUT
      uint8_t noPins[OUTPUT_MAX_PINS] = {255, 255, 255, 255, 255};
      busConfigs.emplace_back(TYPE_TUBES_NULL, noPins, 0, PIXEL_COUNTS, COL_ORDER_RGB);
      doInitBusses = true;
      Serial.println(F("Tubes: created null logical output"));
      return;
#endif

      constexpr unsigned defDataTypes[] = {LED_TYPES};
      constexpr unsigned defDataPins[] = {DATA_PINS};
      constexpr unsigned defCounts[] = {PIXEL_COUNTS};
      constexpr unsigned defNumTypes = sizeof(defDataTypes) / sizeof(defDataTypes[0]);
      constexpr unsigned defNumPins = sizeof(defDataPins) / sizeof(defDataPins[0]);
      constexpr unsigned defNumCounts = sizeof(defCounts) / sizeof(defCounts[0]);

      unsigned pinsIndex = 0;
      unsigned start = 0;
      for (unsigned i = 0; i < WLED_MAX_BUSSES; i++) {
        uint8_t pins[OUTPUT_MAX_PINS] = {255, 255, 255, 255, 255};
        unsigned dataType = defDataTypes[(i < defNumTypes) ? i : defNumTypes - 1];
        unsigned busPins = Bus::getNumberOfPins(dataType);
        if (pinsIndex + busPins > defNumPins) break;

        for (unsigned j = 0; j < busPins && j < OUTPUT_MAX_PINS; j++) {
          pins[j] = defDataPins[pinsIndex + j];
        }
        pinsIndex += busPins;

        unsigned count = defCounts[(i < defNumCounts) ? i : defNumCounts - 1];
        if (Bus::isPWM(dataType) || Bus::isOnOff(dataType)) count = 1;

        busConfigs.emplace_back(dataType, pins, start, count, DEFAULT_LED_COLOR_ORDER, false, 0, RGBW_MODE_MANUAL_ONLY, 0, LED_MILLIAMPS_DEFAULT, ABL_MILLIAMPS_DEFAULT, 0);
        start += count;
      }

      if (!busConfigs.empty()) {
        doInitBusses = true;
        Serial.println(F("Tubes: recovered default LED bus config"));
      }
    }

    void recoverLedSegmentsIfNeeded() {
      if (checkedLedSegments || doInitBusses || strip.getLengthTotal() == 0 || BusManager::getNumBusses() == 0) return;

      bool needsSegments = strip.getSegmentsNum() == 0;
      if (!needsSegments) {
        const Segment& seg = strip.getMainSegment();
        needsSegments = seg.length() == 0 || seg.start >= strip.getLengthTotal();
      }

      if (needsSegments) {
        strip.makeAutoSegments(true);
        Serial.println(F("Tubes: recovered LED segment config"));
      }
      checkedLedSegments = true;
    }

  public:
    // AI: below section was generated by an AI
    // Supplies the board UI with a fixed-size snapshot of existing Tubes state.
    void readS3FieldStatus(TubesS3FieldStatus &status) const {
      status.isMaster = controller.isMasterRole();
      status.powerSave = controller.power_save;
      status.role = static_cast<uint8_t>(controller.role);
      status.patternId = controller.current_state.pattern_id;
      status.paletteId = controller.current_state.palette_id;
      status.bpm = controller.current_state.bpm >> 8;
      status.beat = (controller.current_state.beat_frame >> 8) % 16;
      status.peerCount = controller.node.peerTelemetry.count();
      const uint16_t length = strip.getLengthTotal();
      for (size_t i = 0; i < TUBES_S3_PREVIEW_PIXELS; i++) {
        const uint16_t pixel = length == 0 ? 0 : static_cast<uint16_t>((i * length) / TUBES_S3_PREVIEW_PIXELS);
        status.preview[i] = length == 0 ? 0 : strip.getPixelColor(pixel);
      }
    }

    bool readS3Peer(size_t index, TubesS3PeerStatus &peer) const {
      const PeerTelemetryEntry *entry = controller.node.peerTelemetry.entry(index);
      if (entry == nullptr) return false;
      peer.nodeId = entry->nodeId;
      peer.uplinkId = entry->uplinkId;
      peer.lastSeenMs = entry->lastSeenMs;
      peer.samples = entry->samples;
      peer.latestRssi = entry->latestRssi;
      peer.minimumRssi = entry->minimumRssi;
      peer.maximumRssi = entry->maximumRssi;
      return true;
    }

    bool readS3Route(TubesS3RouteStatus &route) {
#if defined(TUBES_ENABLE_SPATIAL_PATTERNS) && defined(TUBES_ENABLE_MOBILE_CONDUCTOR)
      route.anchorEnabled = s3AnchorAuthority;
      route.routeValid = controller.node.hasMobileRoute();
      route.shell = controller.node.mobileRouteShell();
      if (s3AnchorAuthority) {
        route.conductorId = controller.node.header.id;
        route.parentId = controller.node.header.id;
        route.routeCost = 0;
        return true;
      }
      if (!controller.node.mobileRoute.valid(millis())) return true;
      route.conductorId = controller.node.mobileRoute.conductorId();
      route.parentId = controller.node.mobileRoute.parentId();
      route.routeCost = controller.node.mobileRoute.cost();
      route.sequence = controller.node.mobileRoute.sequence();
      return true;
#else
      return false;
#endif
    }

    bool s3ForceNext() {
      if (!controller.isMasterRole()) return false;
      controller.force_next();
      return true;
    }

    bool s3SetMasterAuthority(bool enabled) {
      if (controller.isMasterRole() == enabled) return true;
      if (!enabled) s3SetAnchorAuthority(false);
      controller.setRole(enabled ? MasterRole : DefaultRole);
      return true;
    }

    bool s3SetAnchorAuthority(bool enabled) {
#ifdef TUBES_ENABLE_MOBILE_CONDUCTOR
      if (enabled && !controller.isMasterRole()) return false;
      s3AnchorAuthority = enabled;
      controller.node.setMobileConductorAuthority(enabled);
      return true;
#else
      return false;
#endif
    }
    // AI: end

    void setup() {

      if (PinManager::isPinOk(MASTER_PIN)) {
        pinMode(MASTER_PIN, INPUT_PULLUP);
        if(PinManager::isPinOk(LEGACY_PIN)) {
          pinMode(LEGACY_PIN, INPUT_PULLUP);
        }
        if (digitalRead(MASTER_PIN) == LOW) {
        }
        isLegacy = (digitalRead(MASTER_PIN) == LOW);
      }
      randomize();

      // Override some behaviors on all Tubes
      bootPreset = 0;  // Try to prevent initial playlists from starting
      transitionDelay = 8000;   // Fade them for a long time
      strip.setTransition(transitionDelay);
      strip.setTargetFps(60);
      strip.setCCT(100);
      recoverLedBussesIfNeeded();

      // Start timing
      globalTimer.setup();
      controller.setup();
#ifdef TUBES_S3_FIELD_OS
      // Anchor transmission is an explicit field action, never a boot default.
      s3SetAnchorAuthority(false);
#endif
      if (controller.isMasterRole()) {
#ifndef TUBES_S3_FIELD_OS
        master.setup();
#endif
      }
      debug.setup();
    }

    void loop()
    {
      if (otaSuspended) return;

      EVERY_N_MILLISECONDS(10000) {
        randomize();
      }

      globalTimer.update();
      recoverLedSegmentsIfNeeded();

      if (controller.isMasterRole()) {
#ifndef TUBES_S3_FIELD_OS
        master.update();
#endif
      }
      controller.update();
      debug.update();

      // Draw after everything else is done
      controller.led_strip.update();
    }

    void handleOverlayDraw() {
      if (otaSuspended) return;

      // Draw effects layers over whatever WLED is doing.
      controller.handleOverlayDraw();
      debug.handleOverlayDraw();
      if (controller.isMasterRole()) {
        master.handleOverlayDraw();
      }

      // When AP mode is on, make sure it's obvious
      // Blink when there's a connected client
      if (apActive) {
        strip.setPixelColor(0, CRGB::Purple);
        if (millis() % 4000 > 1000 && WiFi.softAPgetStationNum()) {
          strip.setPixelColor(0, CRGB::Black);
        }
        strip.setPixelColor(1, CRGB::Black);
      }
    }

    bool handleButton(uint8_t b) {
      // Special code for handling the "power save" button
      if (b == 100) { // Press button 0 for WLED_LONG_POWER_SAVE ms
        controller.togglePowerSave();
        return true;
      }
      if (b == 101) { // Short press button 0 (piggybacks with default)
        controller.cancelOverrides();
        return true;
      }
      if (b == 102) { // Double-click button 0
        controller.acknowledge();
        if (controller.isSelecting()) {
          if (controller.isSelected())
            controller.deselect();
          else
            controller.select();
        } else {
          controller.request_new_bpm();
        }
        return true;
      }

      return false;
    }

    void onUpdateBegin(bool init) override {
      if (init) {
#ifdef TUBES_ENABLE_HTTP_OTA_VFX
        // This acknowledges only entry into HTTP OTA. Success remains the next boot's responsibility.
        constexpr uint32_t PULSE_MS = 80;
        for (uint8_t pulse = 0; pulse < 2; pulse++) {
          showOtaAcknowledgement(CRGB(128, 0, 180));
          const uint32_t onStarted = millis();
          while (millis() - onStarted < PULSE_MS) delay(1);
          showOtaAcknowledgement(CRGB::Black);
          const uint32_t offStarted = millis();
          while (millis() - offStarted < PULSE_MS) delay(1);
        }
#endif
        otaSuspended = true;
        return;
      }

      otaSuspended = false;
#ifdef TUBES_ENABLE_HTTP_OTA_VFX
      showOtaAcknowledgement(CRGB::Black);
#endif
    }

#ifdef TUBES_ENABLE_SPATIAL_PATTERNS
    void addToConfig(JsonObject &root) override {
      JsonObject top = root.createNestedObject(F("Tubes"));
      top[F("spatial-mode")] = static_cast<uint8_t>(spatialMode);
    }

    bool readFromConfig(JsonObject &root) override {
      JsonObject top = root[F("Tubes")];
      const int configuredMode = top[F("spatial-mode")] | 0;
      spatialMode = TubesExperiment::parseSpatialMode(configuredMode);
      controller.setSpatialMode(spatialMode);
      return !top[F("spatial-mode")].isNull();
    }

    void appendConfigData() override {
      oappend(F("dd=addDropdown('Tubes','spatial-mode');"));
      oappend(F("addOption(dd,'Off','0');"));
      oappend(F("addOption(dd,'Latency','1');"));
      oappend(F("addOption(dd,'BPM drift','2');"));
    }
#endif

    uint16_t getId() override { return USERMOD_ID_TUBES; }
};
