#ifdef WAVESHARE_S3_TUBES_REMOTE

// AI: below section was generated by an AI
// Attribution: uses Arduino_GFX, SensorLib, XPowersLib, and WLED Tubes APIs
// following the Waveshare ESP32-S3-Touch-AMOLED-2.16 vendor documentation.

#include "wled.h"

#undef BLACK
#undef BLUE
#undef GREEN
#undef CYAN
#undef RED
#undef MAGENTA
#undef YELLOW
#undef WHITE
#undef ORANGE
#undef PURPLE
#undef DARKGREY

#include <Arduino_GFX_Library.h>
#include <SensorQMI8658.hpp>
#include <touch/TouchDrvCST92xx.h>
#include <XPowersLib.h>

#ifdef TUBES_S3_FIELD_OS
#include "../Tubes/s3_field_api.h"
#include "../Tubes/device_report_protocol.h"
#endif

namespace {
constexpr int8_t DISPLAY_CS = 12;
constexpr int8_t DISPLAY_SCLK = 38;
constexpr int8_t DISPLAY_SDIO0 = 4;
constexpr int8_t DISPLAY_SDIO1 = 5;
constexpr int8_t DISPLAY_SDIO2 = 6;
constexpr int8_t DISPLAY_SDIO3 = 7;
constexpr int8_t DISPLAY_RESET = 39;
constexpr int8_t PERIPHERAL_SDA = 15;
constexpr int8_t PERIPHERAL_SCL = 14;
constexpr int8_t TOUCH_IRQ = 11;
constexpr int8_t TOUCH_RESET = 40;
constexpr int16_t DISPLAY_WIDTH = 480;
constexpr int16_t DISPLAY_HEIGHT = 480;
constexpr uint32_t SAMPLE_INTERVAL_MS = 1000;
constexpr uint32_t PREVIEW_INTERVAL_MS = 100;
#ifdef TUBES_S3_FIELD_OS
constexpr uint8_t FIELD_OS_DEFAULT_BRIGHTNESS = 255;
#else
constexpr uint8_t SMOKE_DEFAULT_BRIGHTNESS = 160;
#endif

volatile bool touchInterruptPending = false;

void IRAM_ATTR handleTouchInterrupt() {
  touchInterruptPending = true;
}

Arduino_ESP32QSPI displayBus(DISPLAY_CS, DISPLAY_SCLK, DISPLAY_SDIO0, DISPLAY_SDIO1,
                             DISPLAY_SDIO2, DISPLAY_SDIO3);
Arduino_CO5300 display(&displayBus, DISPLAY_RESET, 0, false, DISPLAY_WIDTH, DISPLAY_HEIGHT);
TouchDrvCST92xx touch;
SensorQMI8658 imu;
XPowersPMU pmu;

#ifdef TUBES_S3_FIELD_OS
enum class FieldViewId : uint8_t {
  Home,
  Conductor,
  Surveyor,
  Update,
  Channels
};

class WaveshareS3FieldOs : public Usermod {
private:
  struct Rect {
    int16_t x;
    int16_t y;
    int16_t width;
    int16_t height;

    bool contains(int16_t px, int16_t py) const {
      return px >= x && py >= y && px < x + width && py < y + height;
    }
  };

  struct ButtonComponent {
    Rect bounds;
    uint16_t color;
    const __FlashStringHelper *label;
  };

  struct DeviceCard {
    uint16_t id;
    uint16_t version;
    uint16_t uplinkId;
    uint32_t ageSeconds;
    const char *kind;

    DeviceCard(uint16_t id, uint16_t version, uint16_t uplinkId,
               uint32_t ageSeconds, const char *kind)
        : id(id), version(version), uplinkId(uplinkId), ageSeconds(ageSeconds), kind(kind) {}
  };

  bool displayReady = false;
  bool touchReady = false;
  bool nextSendFailed = false;
  bool touchDown = false;
  bool propagationSeedAttempted = false;
  bool propagationSeedSent = false;

  static constexpr uint16_t COLOR_BACKGROUND = 0x0863;
  static constexpr uint16_t COLOR_SURFACE = 0x10E7;
  static constexpr uint16_t COLOR_SURFACE_RAISED = 0x194A;
  static constexpr uint16_t COLOR_PRIMARY = 0x64FF;
  static constexpr uint16_t COLOR_MINT = 0x5F56;
  static constexpr uint16_t COLOR_AMBER = 0xFDC8;
  static constexpr uint16_t COLOR_MUTED = 0x8C51;

  static uint16_t rgb565(uint32_t color) {
    // Production colors stay RGB888 until this existing color-depth conversion.
    // This is not gamma or brightness scaling.
    const uint8_t red = color >> 16;
    const uint8_t green = color >> 8;
    const uint8_t blue = color;
    return static_cast<uint16_t>(((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3));
  }

  void drawChrome(const __FlashStringHelper *text, bool showHome) {
    display.fillScreen(COLOR_BACKGROUND);
    display.setTextWrap(false);
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(24, 22);
    display.println(text);
    if (showHome) drawButton({{372, 12, 88, 48}, COLOR_SURFACE_RAISED, F("Home")});
  }

  void drawButton(const ButtonComponent &button) {
    const Rect &bounds = button.bounds;
    display.fillRoundRect(bounds.x, bounds.y, bounds.width, bounds.height, 20, button.color);
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(bounds.x + 16, bounds.y + bounds.height / 2 - 8);
    display.println(button.label);
  }

  void drawHomeContent() {
    display.setTextColor(COLOR_MUTED);
    display.setTextSize(1);
    display.setCursor(25, 51);
    display.println(F("The flock stays live wherever you go"));
    drawButton({{20, 84, 210, 150}, COLOR_PRIMARY, F("Conductor")});
    drawButton({{250, 84, 210, 150}, COLOR_SURFACE_RAISED, F("Surveyor")});
    drawButton({{20, 250, 210, 150}, COLOR_SURFACE_RAISED, F("Update")});
    drawButton({{250, 250, 210, 150}, COLOR_SURFACE_RAISED, F("Channels")});
  }

  // Persistent Strip observes WLED's canonical, completed logical framebuffer.
  // The null bus supplies geometry only; it must not become a second pixel store.
  class Strip {
  public:
    void draw(int16_t x, int16_t y, int16_t width, int16_t height, bool force = false) {
      const int16_t cell = width / 60;
      uint32_t colors[60];
      const bool validTopology = ::strip.getLengthTotal() >= 60;
      // draw() runs periodically, so this samples the previous completed show frame.
      for (uint8_t i = 0; i < 60; i++) colors[i] = validTopology ? ::strip.getPixelColor(i) : 0;
      for (uint8_t i = 0; i < 60; i++) {
        if (force || !initialized || colors[i] != previous[i])
          fillCell(x + i * cell, y, cell, height, colors[i]);
        previous[i] = colors[i];
      }
      initialized = true;
    }
  private:
    uint32_t previous[60] = {};
    bool initialized = false;

    void fillCell(int16_t x, int16_t y, int16_t w, int16_t h, uint32_t color) {
      display.fillRect(x, y, w - 1, h, rgb565(color));
    }
  };

  Strip stripComponent;

  void drawConductorTelemetry(const TubesS3FieldStatus &status) {
    display.fillRect(20, 68, 440, 108, COLOR_BACKGROUND);
    drawDeviceCard(68, {status.localNodeId, status.tubesVersion, status.uplinkId,
                       UINT32_MAX, "THIS DEVICE"});
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(24, 132);
    display.printf("%s\n", status.patternName);
    display.setTextColor(COLOR_MUTED);
    display.setTextSize(1);
    display.setCursor(24, 154);
    display.printf("%s  |  %u BPM  |  beat %u\n",
                   status.isMaster ? "LEADING" : status.isFollowing ? "FOLLOWING" : "UNLINKED",
                   status.bpm, status.beat + 1);
    display.setCursor(260, 154);
    if (!status.radioReady) {
      display.setTextColor(RGB565_RED);
      display.printf("Radio offline  |  channel %u\n", status.radioChannel);
    } else {
      display.setTextColor(COLOR_MINT);
      const uint32_t targetFrame = static_cast<uint32_t>(status.nextPatternPhrase) << 12;
      const int32_t remainingFrames = static_cast<int32_t>(targetFrame - status.beatFrame);
      if (status.bpm == 0 || remainingFrames <= 0) {
        display.printf("Live blend  |  next pattern %u\n", status.nextPatternId);
      } else {
        const uint32_t tenths = (static_cast<uint64_t>(remainingFrames) * 600U
            + static_cast<uint32_t>(status.bpm) * 128U)
            / (static_cast<uint32_t>(status.bpm) * 256U);
        display.printf("Pattern %u in %lu.%lus  |  blending live\n", status.nextPatternId,
            tenths / 10, tenths % 10);
      }
    }
  }

  void drawConductorContent(bool full) {
    TubesS3FieldStatus status;
    tubesS3ReadStatus(status);
    drawConductorTelemetry(status);
    stripComponent.draw(31, 178, 420, 110, full);
    if (!status.canForceNext)
      drawButton({{120, 328, 240, 70}, COLOR_MUTED, F("Next unavailable")});
    else if (nextSendFailed)
      drawButton({{120, 328, 240, 70}, RGB565_RED, F("Next failed")});
    else
      drawButton({{150, 328, 180, 70}, COLOR_PRIMARY, F("Next")});
  }

  static bool surveyorBefore(const TubesS3PeerStatus &candidate, const TubesS3PeerStatus &prior) {
    if (candidate.rssiKnown != prior.rssiKnown) return candidate.rssiKnown;
    if (candidate.rssiKnown && candidate.latestRssi != prior.latestRssi)
      return candidate.latestRssi > prior.latestRssi;
    return candidate.nodeId < prior.nodeId;
  }

  static uint32_t mixRevision(uint32_t value, uint32_t field) {
    return (value ^ field) * 16777619UL;
  }

  uint32_t conductorRevision(const TubesS3FieldStatus &status) {
    uint32_t value = mixRevision(status.localNodeId, status.tubesVersion);
    value = mixRevision(value, status.uplinkId);
    value = mixRevision(value, status.patternId | (status.nextPatternId << 8));
    value = mixRevision(value, status.paletteId | (status.nextPaletteId << 8));
    value = mixRevision(value, status.bpm | (status.beat << 16));
    value = mixRevision(value, status.currentPatternPhrase);
    value = mixRevision(value, status.nextPatternPhrase);
    value = mixRevision(value, status.radioReady | (status.radioChannel << 8));
    value = mixRevision(value, status.isMaster | (status.isFollowing << 1));
    return value;
  }

  bool isSeedableDig2GoTarget(const TubesS3CarrierTarget &target) {
    if (!target.nodeId || target.family != TubeHardwareDig2Go
        || target.variant != TubeVariantStandard) return false;
    for (size_t index = 0; index < tubesS3CarrierArtifactCount(); index++) {
      TubesS3CarrierArtifact artifact;
      if (!tubesS3ReadCarrierArtifact(index, artifact)) continue;
      if (artifact.family == target.family && artifact.variant == target.variant
          && artifact.release == target.release && artifact.size > 0) return true;
    }
    return false;
  }

  void drawDeviceCard(int16_t y, const DeviceCard &device,
                      uint16_t color = COLOR_SURFACE_RAISED) {
    display.fillRoundRect(20, y, 440, 62, 10, color);
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(34, y + 7);
    display.printf("%s", device.kind);
    display.setTextSize(1);
    display.setCursor(34, y + 31);
    if (device.id) display.printf("ID: %04X", device.id);
    else display.print(F("ID: UNKNOWN"));
    display.print(F(" | VERSION: "));
    if (device.version) display.printf("v%u", device.version);
    else display.print(F("UNKNOWN"));
    display.setTextColor(COLOR_MUTED);
    display.setTextSize(1);
    display.setCursor(34, y + 49);
    if (device.uplinkId) display.printf("UPLINK: %04X", device.uplinkId);
    else display.print(F("UPLINK: NONE"));
    if (device.ageSeconds != UINT32_MAX)
      display.printf(" | HEARD: %lus AGO", device.ageSeconds);
  }

  void drawChannelCard(int16_t y, const char *name, const TubesS3ChannelStatus &channel,
                      const char *currentValue) {
    display.fillRoundRect(20, y, 440, 70, 10, COLOR_SURFACE_RAISED);
    display.setTextColor(COLOR_MUTED);
    display.setTextSize(1);
    display.setCursor(34, y + 10);
    display.printf("%s CHANNEL  |  READ ONLY", name);
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(34, y + 27);
    display.printf("%s: %s", name, currentValue);
    display.setTextColor(COLOR_MUTED);
    display.setTextSize(1);
    display.setCursor(34, y + 55);
    if (channel.active)
      display.printf("Owned by channel %03X / control %03X", channel.ownerChannelId,
          channel.ownerControlId);
    else
      display.printf("Local channel %03X / unclaimed", channel.localChannelId);
  }

  void drawSurveyorContent() {
    TubesS3FieldStatus status;
    tubesS3ReadStatus(status);
    display.fillRect(20, 70, 440, 370, COLOR_BACKGROUND);
    display.setTextSize(1);
    TubesS3PeerStatus sorted[4];
    size_t shown = 0;
    const uint32_t now = millis();
    for (size_t i = 0; i < status.peerCount; i++) {
      TubesS3PeerStatus candidate;
      if (!tubesS3ReadPeer(i, candidate) || candidate.nodeId == status.localNodeId
          || now - candidate.lastSeenMs > 60000) continue;
      if (shown == 4 && !surveyorBefore(candidate, sorted[3])) continue;
      size_t position = shown < 4 ? shown++ : 3;
      while (position > 0 && surveyorBefore(candidate, sorted[position - 1])) {
        if (position < 4) sorted[position] = sorted[position - 1];
        position--;
      }
      if (position < 4) sorted[position] = candidate;
    }
    display.setTextColor(COLOR_MUTED);
    display.setTextSize(1);
    display.setCursor(24, 76);
    display.println(F("THIS S3"));
    drawDeviceCard(92, {status.localNodeId, status.tubesVersion, status.uplinkId,
                        UINT32_MAX, "THIS DEVICE"});
    display.setTextColor(COLOR_MUTED);
    display.setCursor(24, 160);
    display.println(F("NEARBY DEVICES"));
    if (shown == 0) {
      display.setTextColor(RGB565_WHITE);
      display.setCursor(24, 190);
      display.println(F("No other Tubes heard in the last 60 seconds."));
    }
    for (size_t i = 0; i < shown; i++) {
      const TubesS3PeerStatus &peer = sorted[i];
      drawDeviceCard(178 + i * 66, {peer.nodeId, peer.tubesVersion, peer.uplinkId,
                     (now - peer.lastSeenMs) / 1000, "TUBES DEVICE"});
    }
  }

  void drawChannelsContent() {
    TubesS3FieldStatus status;
    tubesS3ReadStatus(status);
    display.fillRect(20, 70, 440, 370, COLOR_BACKGROUND);
    display.setTextSize(1);
    drawDeviceCard(72, {status.localNodeId, status.tubesVersion, status.uplinkId,
                        UINT32_MAX, "THIS DEVICE"});
    display.setTextColor(COLOR_MUTED);
    display.setCursor(24, 142);
    display.println(F("LIVE CHANNEL AUTHORITY"));
    char beatValue[32];
    char patternValue[32];
    char paletteValue[32];
    snprintf(beatValue, sizeof(beatValue), "%u BPM", status.bpm);
    snprintf(patternValue, sizeof(patternValue), "%s -> %u", status.patternName,
        status.nextPatternId);
    snprintf(paletteValue, sizeof(paletteValue), "%s -> %u", status.paletteName,
        status.nextPaletteId);
    drawChannelCard(156, "BEAT", status.beatChannel, beatValue);
    drawChannelCard(232, "PATTERN", status.patternChannel, patternValue);
    drawChannelCard(308, "PALETTE", status.paletteChannel, paletteValue);
  }

  void drawUpdateContent() {
    display.fillRect(20, 68, 440, 372, COLOR_BACKGROUND);
#ifdef TUBES_S3_FIRMWARE_CARRIER
    TubesS3FieldStatus status;
    tubesS3ReadStatus(status);
    display.setTextColor(COLOR_MUTED);
    display.setTextSize(1);
    display.setCursor(24, 72);
    display.println(F("THIS S3 UPDATE CARRIER"));
    drawDeviceCard(88, {status.localNodeId, status.tubesVersion, status.uplinkId,
                        UINT32_MAX, "THIS DEVICE"});
    display.setTextColor(COLOR_MUTED);
    display.setCursor(24, 158);
    display.println(F("EMBEDDED FIRMWARE"));
    for (size_t index = 0; index < tubesS3CarrierArtifactCount(); index++) {
      TubesS3CarrierArtifact artifact;
      const int16_t y = 174 + index * 38;
      display.fillRoundRect(20, y, 440, 32, 8, COLOR_SURFACE_RAISED);
      display.setTextColor(RGB565_WHITE);
      display.setTextSize(2);
      display.setCursor(32, y + 11);
      if (!tubesS3ReadCarrierArtifact(index, artifact)) {
        display.print(F("ARTIFACT UNAVAILABLE"));
      } else {
        if (artifact.family == TubeHardwareDig2Go) display.print(F("DIG2GO"));
        else if (artifact.family == TubeHardwareAthomC3) display.print(F("ATHOM C3"));
        else display.print(F("UNKNOWN TARGET"));
        if (artifact.peerPropagation) display.print(F(" | P2P | v"));
        else if (artifact.variant == TubeVariantStandard) display.print(F(" | STANDARD | v"));
        else display.print(F(" | VARIANT UNKNOWN | v"));
        display.print(artifact.release);
      }
    }
    drawButton({{20, 258, 150, 46}, COLOR_PRIMARY, F("Scan")});
    TubesS3CarrierStatus carrier;
    tubesS3ReadCarrierStatus(carrier);
    display.setTextSize(1);
    display.setTextColor(COLOR_MUTED);
    display.setCursor(190, 276);
    display.printf("Carrier state %u  |  release %u\n", carrier.state, carrier.release);
    if (propagationSeedAttempted) {
      display.setCursor(190, 292);
      display.setTextColor(propagationSeedSent ? COLOR_MINT : RGB565_RED);
      display.print(propagationSeedSent ? F("SEED REQUEST SENT") : F("SEED REQUEST FAILED"));
    }
    display.setCursor(24, 316);
    display.println(F("DISCOVERED UPDATE TARGETS"));
    const size_t count = tubesS3CarrierTargetCount();
    display.setTextColor(RGB565_WHITE);
    if (count == 0) {
      display.setTextSize(2);
      display.setCursor(24, 348);
      display.println(F("NO DEVICES NEARBY"));
    }
    for (size_t index = 0; index < count && index < 2; index++) {
      TubesS3CarrierTarget target;
      if (!tubesS3ReadCarrierTarget(index, target)) continue;
      const int16_t y = 332 + index * 66;
      const bool seedable = isSeedableDig2GoTarget(target);
      drawDeviceCard(y, {target.nodeId, target.release, target.uplinkId,
                     (millis() - target.lastSeenMs) / 1000,
                     seedable ? "DIG2GO / TAP TO SEED P2P"
                       : target.family == TubeHardwareDig2Go
                         ? "DIG2GO / TAP TO UPDATE" : "C3 / TAP TO UPDATE"});
    }
#else
    display.setTextColor(COLOR_MUTED);
    display.setTextSize(2);
    display.setCursor(36, 120);
    display.println(F("Carrier build required"));
    display.setTextSize(1);
    display.setCursor(36, 166);
    display.println(F("This base firmware does not carry device images."));
#endif
  }

  class FieldView {
  public:
    FieldView(WaveshareS3FieldOs &owner, FieldViewId id,
              const __FlashStringHelper *title, uint32_t refreshMs)
        : owner(owner), viewId(id), viewTitle(title), refreshIntervalMs(refreshMs) {}
    virtual ~FieldView() = default;

    FieldViewId id() const { return viewId; }
    void render(bool full) {
      if (full) owner.drawChrome(viewTitle, viewId != FieldViewId::Home);
      renderContent(full);
      lastRefreshMs = millis();
      lastRevision = revision();
    }
    virtual FieldViewId tap(int16_t, int16_t) { return viewId; }
    virtual void tick(uint32_t now) {
      if (refreshIntervalMs && now - lastRefreshMs >= refreshIntervalMs) {
        lastRefreshMs = now;
        const uint32_t nextRevision = revision();
        if (nextRevision != lastRevision) render(false);
      }
    }

  protected:
    WaveshareS3FieldOs &owner;
    virtual void renderContent(bool full) = 0;
    uint32_t lastRefreshMs = 0;
    virtual uint32_t revision() { return 0; }

  private:
    FieldViewId viewId;
    const __FlashStringHelper *viewTitle;
    uint32_t refreshIntervalMs;
    uint32_t lastRevision = 0;
  };

  class HomeView final : public FieldView {
  public:
    explicit HomeView(WaveshareS3FieldOs &owner)
        : FieldView(owner, FieldViewId::Home, F("Tubes Field OS"), 0) {}
    FieldViewId tap(int16_t x, int16_t y) override {
      if (Rect{20, 84, 210, 150}.contains(x, y)) return FieldViewId::Conductor;
      if (Rect{250, 84, 210, 150}.contains(x, y)) return FieldViewId::Surveyor;
      if (Rect{20, 250, 210, 150}.contains(x, y)) return FieldViewId::Update;
      if (Rect{250, 250, 210, 150}.contains(x, y)) return FieldViewId::Channels;
      return FieldViewId::Home;
    }
  protected:
    void renderContent(bool) override { owner.drawHomeContent(); }
  };

  class ConductorView final : public FieldView {
  public:
    explicit ConductorView(WaveshareS3FieldOs &owner)
        : FieldView(owner, FieldViewId::Conductor, F("Conductor"), 0) {}
    FieldViewId tap(int16_t x, int16_t y) override {
      if (Rect{120, 315, 240, 100}.contains(x, y)) {
        TubesS3FieldStatus status;
        tubesS3ReadStatus(status);
        if (status.canForceNext) {
          owner.nextSendFailed = !tubesS3ForceNext();
          owner.drawConductorContent(false);
        }
      }
      return FieldViewId::Conductor;
    }
    void tick(uint32_t now) override {
      if (now - lastPreviewMs >= PREVIEW_INTERVAL_MS) {
        lastPreviewMs = now;
        owner.stripComponent.draw(31, 178, 420, 110);
      }
      if (now - lastRefreshMs >= SAMPLE_INTERVAL_MS) {
        TubesS3FieldStatus status;
        tubesS3ReadStatus(status);
        const uint32_t nextRevision = owner.conductorRevision(status);
        if (nextRevision != lastTelemetryRevision) {
          owner.drawConductorTelemetry(status);
          lastTelemetryRevision = nextRevision;
        }
        lastRefreshMs = now;
      }
    }
  protected:
    void renderContent(bool full) override {
      owner.drawConductorContent(full);
      lastPreviewMs = millis();
      TubesS3FieldStatus status;
      tubesS3ReadStatus(status);
      lastTelemetryRevision = owner.conductorRevision(status);
    }
  private:
    uint32_t lastPreviewMs = 0;
    uint32_t lastTelemetryRevision = 0;
  };

  class SurveyorView final : public FieldView {
  public:
    explicit SurveyorView(WaveshareS3FieldOs &owner)
        : FieldView(owner, FieldViewId::Surveyor, F("Surveyor"), SAMPLE_INTERVAL_MS) {}
  protected:
    void renderContent(bool) override { owner.drawSurveyorContent(); }
    uint32_t revision() override {
      TubesS3FieldStatus status;
      tubesS3ReadStatus(status);
      uint32_t value = owner.mixRevision(status.localNodeId, status.tubesVersion);
      value = owner.mixRevision(value, status.uplinkId);
      for (size_t index = 0; index < status.peerCount; index++) {
        TubesS3PeerStatus peer;
        if (!tubesS3ReadPeer(index, peer)) continue;
        value = owner.mixRevision(value, peer.nodeId);
        value = owner.mixRevision(value, peer.uplinkId);
        value = owner.mixRevision(value, peer.tubesVersion);
        value = owner.mixRevision(value, (millis() - peer.lastSeenMs) / 5000);
      }
      return value;
    }
  };

  class UpdateView final : public FieldView {
  public:
    explicit UpdateView(WaveshareS3FieldOs &owner)
        : FieldView(owner, FieldViewId::Update, F("Update"), SAMPLE_INTERVAL_MS) {}
    FieldViewId tap(int16_t x, int16_t y) override {
#ifdef TUBES_S3_FIRMWARE_CARRIER
      if (Rect{20, 252, 150, 60}.contains(x, y)) {
        tubesS3ScanCarrierTargets();
      } else if (y >= 326) {
        const size_t index = (y - 332) / 66;
        TubesS3CarrierTarget target;
        if (tubesS3ReadCarrierTarget(index, target)) {
          if (owner.isSeedableDig2GoTarget(target)) {
            owner.propagationSeedAttempted = true;
            owner.propagationSeedSent = tubesS3SeedDig2GoPropagation(target.nodeId);
          } else {
            tubesS3ArmCarrier(target.mac, target.family, target.variant, target.release);
          }
        }
      }
#endif
      return FieldViewId::Update;
    }
  protected:
    void renderContent(bool) override { owner.drawUpdateContent(); }
    uint32_t revision() override {
#ifdef TUBES_S3_FIRMWARE_CARRIER
      TubesS3CarrierStatus carrier;
      tubesS3ReadCarrierStatus(carrier);
      uint32_t value = owner.mixRevision(carrier.state, carrier.release);
      value = owner.mixRevision(value, owner.propagationSeedAttempted);
      value = owner.mixRevision(value, owner.propagationSeedSent);
      const size_t count = tubesS3CarrierTargetCount();
      value = owner.mixRevision(value, count);
      for (size_t index = 0; index < count; index++) {
        TubesS3CarrierTarget target;
        if (!tubesS3ReadCarrierTarget(index, target)) continue;
        value = owner.mixRevision(value, target.nodeId);
        value = owner.mixRevision(value, target.uplinkId);
        value = owner.mixRevision(value, target.release);
        value = owner.mixRevision(value, (millis() - target.lastSeenMs) / 5000);
      }
      return value;
#else
      return 0;
#endif
    }
  };

  class ChannelsView final : public FieldView {
  public:
    explicit ChannelsView(WaveshareS3FieldOs &owner)
        : FieldView(owner, FieldViewId::Channels, F("Channels"), SAMPLE_INTERVAL_MS) {}
  protected:
    void renderContent(bool) override { owner.drawChannelsContent(); }
    uint32_t revision() override {
      TubesS3FieldStatus status;
      tubesS3ReadStatus(status);
      uint32_t value = owner.mixRevision(status.bpm, status.beatChannel.active);
      value = owner.mixRevision(value, status.patternId | (status.nextPatternId << 8));
      value = owner.mixRevision(value, status.paletteId | (status.nextPaletteId << 8));
      value = owner.mixRevision(value, status.beatChannel.ownerChannelId);
      value = owner.mixRevision(value, status.beatChannel.ownerControlId);
      value = owner.mixRevision(value, status.beatChannel.active);
      value = owner.mixRevision(value, status.beatChannel.localChannelId);
      value = owner.mixRevision(value, status.patternChannel.ownerChannelId);
      value = owner.mixRevision(value, status.patternChannel.ownerControlId);
      value = owner.mixRevision(value, status.patternChannel.active);
      value = owner.mixRevision(value, status.patternChannel.localChannelId);
      value = owner.mixRevision(value, status.paletteChannel.ownerChannelId);
      value = owner.mixRevision(value, status.paletteChannel.ownerControlId);
      value = owner.mixRevision(value, status.paletteChannel.active);
      value = owner.mixRevision(value, status.paletteChannel.localChannelId);
      return value;
    }
  };

  class ViewManager {
  public:
    ViewManager(WaveshareS3FieldOs &owner, HomeView &home, ConductorView &conductor,
                SurveyorView &surveyor, UpdateView &update, ChannelsView &channels)
        : owner(owner), home(home), conductor(conductor), surveyor(surveyor),
          update(update), channels(channels), active(&home) {}

    void begin() { active->render(true); }
    void tick(uint32_t now) { active->tick(now); }
    void tap(int16_t x, int16_t y) {
      if (active->id() != FieldViewId::Home && Rect{360, 0, 120, 75}.contains(x, y)) {
        navigate(FieldViewId::Home);
        return;
      }
      const FieldViewId destination = active->tap(x, y);
      if (destination != active->id()) navigate(destination);
    }

  private:
    void navigate(FieldViewId id) {
      active = view(id);
      active->render(true);
    }
    FieldView *view(FieldViewId id) {
      switch (id) {
        case FieldViewId::Conductor: return &conductor;
        case FieldViewId::Surveyor: return &surveyor;
        case FieldViewId::Update: return &update;
        case FieldViewId::Channels: return &channels;
        case FieldViewId::Home: default: return &home;
      }
    }

    WaveshareS3FieldOs &owner;
    HomeView &home;
    ConductorView &conductor;
    SurveyorView &surveyor;
    UpdateView &update;
    ChannelsView &channels;
    FieldView *active;
  };

  HomeView homeView;
  ConductorView conductorView;
  SurveyorView surveyorView;
  UpdateView updateView;
  ChannelsView channelsView;
  ViewManager viewManager;

public:
  WaveshareS3FieldOs()
      : homeView(*this), conductorView(*this), surveyorView(*this), updateView(*this),
        channelsView(*this),
        viewManager(*this, homeView, conductorView, surveyorView, updateView, channelsView) {}

  void setup() override {
    Wire.begin(PERIPHERAL_SDA, PERIPHERAL_SCL);
    displayReady = display.begin();
    if (displayReady) {
      display.setBrightness(
#ifdef TUBES_S3_FIELD_OS
        FIELD_OS_DEFAULT_BRIGHTNESS
#else
        SMOKE_DEFAULT_BRIGHTNESS
#endif
      );
      display.setTextWrap(false);
    }
    pinMode(TOUCH_RESET, OUTPUT);
    digitalWrite(TOUCH_RESET, LOW);
    delay(10);
    digitalWrite(TOUCH_RESET, HIGH);
    delay(50);
    pinMode(TOUCH_IRQ, INPUT_PULLUP);
    touchReady = touch.begin(Wire, CST92XX_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (touchReady) {
      touch.setMaxCoordinates(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      touchInterruptPending = false;
      attachInterrupt(TOUCH_IRQ, handleTouchInterrupt, FALLING);
    }
    if (displayReady) viewManager.begin();
  }

  void loop() override {
    if (touchReady && touchInterruptPending) {
      touchInterruptPending = false;
      int16_t x = -1;
      int16_t y = -1;
      const bool pressed = touch.getPoint(&x, &y, 1) > 0;
      if (pressed && !touchDown) viewManager.tap(x, y);
      touchDown = pressed;
    }
    if (displayReady) viewManager.tick(millis());
  }

  void addToJsonInfo(JsonObject &root) override {
    JsonObject user = root[F("u")];
    if (user.isNull()) user = root.createNestedObject(F("u"));
    JsonArray fieldOs = user.createNestedArray(F("S3 field OS"));
    fieldOs.add(displayReady ? F("display OK") : F("display FAIL"));
    fieldOs.add(touchReady ? F("touch OK") : F("touch FAIL"));
  }
};

static WaveshareS3FieldOs waveshareS3FieldOs;
REGISTER_USERMOD(waveshareS3FieldOs);
#else

class WaveshareS3PeripheralSmoke : public Usermod {
private:
  bool displayReady = false;
  bool touchReady = false;
  bool pmuReady = false;
  bool imuReady = false;
  uint8_t displayBrightness =
#ifdef TUBES_S3_FIELD_OS
    FIELD_OS_DEFAULT_BRIGHTNESS;
#else
    SMOKE_DEFAULT_BRIGHTNESS;
#endif
  uint32_t lastSample = 0;
  int16_t touchX = -1;
  int16_t touchY = -1;
  uint16_t batteryMv = 0;
  bool usbPresent = false;
  bool charging = false;
  float accelX = 0.0f;
  float accelY = 0.0f;
  float accelZ = 0.0f;

  // Samples only board-local peripherals and never enters a Tubes transport path.
  void samplePeripherals() {
    if (pmuReady) {
      batteryMv = pmu.getBattVoltage();
      usbPresent = pmu.isVbusIn();
      charging = pmu.isCharging();
    }

    if (imuReady) imu.getAccelerometer(accelX, accelY, accelZ);

  }

  // Consumes the CST9217's falling-edge notification before its short IRQ pulse is lost.
  void sampleTouch() {
    if (!touchReady || !touchInterruptPending) return;
    touchInterruptPending = false;
    int16_t x = -1;
    int16_t y = -1;
    if (touch.getPoint(&x, &y, 1) > 0) {
      touchX = x;
      touchY = y;
    }
  }

  // Paints a stable diagnostic surface intended for first hardware bring-up.
  void drawStatus() {
    if (!displayReady) return;

    display.fillScreen(RGB565_BLACK);
    display.setCursor(12, 14);
    display.setTextColor(RGB565_CYAN);
    display.setTextSize(2);
    display.println(F("WLEDTubes S3 smoke"));
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(12, 62);
    display.print(F("Display  OK   BRI "));
    display.println(displayBrightness);
    display.setCursor(12, 104);
    display.print(F("Touch    "));
    display.print(touchReady ? F("OK") : F("FAIL"));
    display.print(F("   "));
    display.print(touchX);
    display.print(F(","));
    display.println(touchY);
    display.setCursor(12, 146);
    display.print(F("PMU      "));
    display.print(pmuReady ? F("OK") : F("FAIL"));
    display.print(F("   "));
    display.print(batteryMv);
    display.println(F(" mV"));
    display.setCursor(12, 188);
    display.print(F("USB      "));
    display.print(usbPresent ? F("YES") : F("NO"));
    display.print(F("   CHG "));
    display.println(charging ? F("YES") : F("NO"));
    display.setCursor(12, 230);
    display.print(F("IMU      "));
    display.println(imuReady ? F("OK") : F("FAIL"));
    display.setCursor(12, 272);
    display.print(F("ACC X "));
    display.println(accelX, 2);
    display.setCursor(12, 314);
    display.print(F("ACC Y "));
    display.println(accelY, 2);
    display.setCursor(12, 356);
    display.print(F("ACC Z "));
    display.println(accelZ, 2);
    display.setTextSize(1);
    display.setTextColor(RGB565_YELLOW);
    display.setCursor(12, 414);
    display.println(F("TOUCH: COORDINATES ONLY"));
    display.setCursor(12, 438);
    display.println(F("No LED output. No smoke-test radio TX."));
  }

public:
  void setup() override {
    Wire.begin(PERIPHERAL_SDA, PERIPHERAL_SCL);

    displayReady = display.begin();
    if (displayReady) {
      display.setBrightness(displayBrightness);
      display.setTextWrap(false);
    }

    pinMode(TOUCH_RESET, OUTPUT);
    digitalWrite(TOUCH_RESET, LOW);
    delay(10);
    digitalWrite(TOUCH_RESET, HIGH);
    delay(50);
    pinMode(TOUCH_IRQ, INPUT_PULLUP);
    touchReady = touch.begin(Wire, CST92XX_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (touchReady) {
      touch.setMaxCoordinates(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      touchInterruptPending = false;
      attachInterrupt(TOUCH_IRQ, handleTouchInterrupt, FALLING);
    }

    pmuReady = pmu.begin(Wire, AXP2101_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (pmuReady) {
      pmu.enableBattVoltageMeasure();
      pmu.enableVbusVoltageMeasure();
    }

    imuReady = imu.begin(Wire, QMI8658_L_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (imuReady) {
      imu.configAccelerometer(SensorQMI8658::ACC_RANGE_2G, SensorQMI8658::ACC_ODR_31_25Hz);
      imu.enableAccelerometer();
    }

    samplePeripherals();
    drawStatus();
  }

  void loop() override {
    sampleTouch();
    const uint32_t now = millis();
    if (now - lastSample < SAMPLE_INTERVAL_MS) return;
    lastSample = now;
    samplePeripherals();
    drawStatus();
  }

  void addToJsonInfo(JsonObject &root) override {
    JsonObject user = root[F("u")];
    if (user.isNull()) user = root.createNestedObject(F("u"));
    JsonArray smoke = user.createNestedArray(F("S3 peripheral smoke"));
    smoke.add(displayReady ? F("display OK") : F("display FAIL"));
    smoke.add(touchReady ? F("touch OK") : F("touch FAIL"));
    smoke.add(pmuReady ? F("PMU OK") : F("PMU FAIL"));
    smoke.add(imuReady ? F("IMU OK") : F("IMU FAIL"));

    JsonArray battery = user.createNestedArray(F("S3 battery"));
    battery.add(batteryMv);
    battery.add(F(" mV"));
    JsonArray power = user.createNestedArray(F("S3 power"));
    power.add(usbPresent ? F("USB") : F("battery"));
    power.add(charging ? F(", charging") : F(""));
  }
};

static WaveshareS3PeripheralSmoke waveshareS3PeripheralSmoke;
REGISTER_USERMOD(waveshareS3PeripheralSmoke);
#endif
} // namespace

// Forced-link anchor for the board-specific PlatformIO environment.
extern "C" void waveshareS3TubesRemoteLinkAnchor() {}
// AI: end

#endif
