import { catalog, makeReceipt, resolveProfile } from "./profiles.mjs";
import { getHardwareArtifacts, makeFirmwareOperationReceipt } from "./firmware-ui.mjs";
import { canFlashLocally, flashFromLaptop } from "./local-flash.mjs";

const state = { boardId: "dig2go", lightId: "referenceTube", powerId: "medium" };
let discoveredArtifact = null;
const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);

function invalidateConfirmation() {
	$("#confirmed").checked = false;
	$("#dryRun").disabled = true;
}

// AI: below section was generated by an AI
// Creates accessible choice cards from the shared profile catalog.
function renderChoices(container, records, selected, kind) {
	container.innerHTML = Object.values(records).map((item) => `<label class="choice ${item.id === selected ? "selected" : ""} ${item.support === "Coming later" ? "disabled" : ""}"><input type="radio" name="${kind}" value="${item.id}" ${item.id === selected ? "checked" : ""} ${item.support === "Coming later" ? "disabled" : ""}>${item.support ? `<b>${item.support}</b>` : ""}<strong>${item.name}</strong><span>${item.summary || item.note || "Repository target; not enabled tonight"}${item.milliamps ? ` · ${item.milliamps} mA` : ""}</span></label>`).join("");
	container.querySelectorAll("input").forEach((input) => input.addEventListener("change", () => {
		state[`${kind}Id`] = input.value;
		invalidateConfirmation();
		container.querySelectorAll(".choice").forEach((card) => card.classList.remove("selected"));
		input.closest(".choice").classList.add("selected");
		if (kind === "light") syncAdvancedLight();
		if (kind === "power") $("#milliamps").value = catalog.power[input.value].milliamps;
	}));
}

function syncAdvancedLight() {
	const light = catalog.lights[state.lightId];
	$("#stripType").value = light.type; $("#colorOrder").value = light.order; $("#pixels").value = light.pixels;
}

function currentPlan() {
	return resolveProfile({ ...state, stripType: $("#stripType").value.trim(), colorOrder: $("#colorOrder").value, pixels: $("#pixels").value, milliamps: $("#milliamps").value });
}

function showPanel(id) {
	document.querySelectorAll(".panel").forEach((panel) => panel.classList.toggle("active", panel.id === id));
	document.querySelectorAll(".step").forEach((step) => step.classList.toggle("active", step.dataset.go === id));
	if (id === "review") renderPlan();
	window.scrollTo({ top: document.querySelector("nav").offsetTop - 18, behavior: "smooth" });
}

function renderPlan() {
	try {
		const p = currentPlan();
		const artifactLabel = discoveredArtifact?.status === "verified-manifest" ? `Verified ${discoveredArtifact.releaseIdentity} · SHA-256 ${discoveredArtifact.sha256.slice(0, 12)}…` : "Unavailable — dry run only";
		$("#plan").innerHTML = `<div class="plan-grid">${[["Hardware firmware",p.resolved.firmwareTarget],["Software profile","Runtime layer · waiting for split protocol"],["LED output",`GPIO ${p.resolved.gpio}`],["Strip",p.resolved.stripType],["Color order",`${p.resolved.colorOrder} (confirm)`],["Logical pixels",p.resolved.logicalPixelCount],["Hard current ceiling",`${p.resolved.currentLimitMilliamps} mA · prototype example`],["Geometry",p.resolved.geometry],["Artifact",artifactLabel]].map(([a,b])=>`<div class="fact"><small>${escapeHtml(a)}</small><strong>${escapeHtml(b)}</strong></div>`).join("")}</div><div class="ownership"><strong>Where settings belong</strong><br>Hardware firmware: bootability, GPIO and compiled capabilities · WLED runtime config: strip, order, pixels and current ceiling · Tubes software profile: palette, tempo, pattern, role and spatial behavior</div>`;
	} catch (error) { $("#plan").innerHTML = `<div class="warning">${error.message}</div>`; }
}

async function selectDevice() {
	if (!("serial" in navigator)) { $("#serialStatus").textContent = "Web Serial is unavailable here. Use desktop Chrome/Edge or continue with Dry Run."; return; }
	try { const port = await navigator.serial.requestPort(); const info = port.getInfo(); $("#serialStatus").textContent = `USB device selected (${info.usbVendorId || "unknown VID"}:${info.usbProductId || "unknown PID"}). Identity is not verified; nothing was opened or written.`; }
	catch (error) { $("#serialStatus").textContent = error.name === "NotFoundError" ? "No device selected. Nothing changed." : `Selection failed safely: ${error.message}`; }
}

function completeDryRun() {
	const receipt = makeReceipt(currentPlan(), new Date(), discoveredArtifact);
	$("#receipt").textContent = JSON.stringify(receipt, null, 2);
	$("#receiptPanel").hidden = false;
	$("#receiptPanel").scrollIntoView({ behavior: "smooth" });
}

function addText(parent, tag, value, className) { const element = document.createElement(tag); element.textContent = String(value); if (className) element.className = className; parent.append(element); return element; }
function formatBytes(bytes) { return `${bytes.toLocaleString()} bytes`; }

// AI: below section was generated by an AI
// Renders fetched manifest fields as text nodes and keeps bench state separate from the participant plan.
function appendFirmwareCards(container, variants) {
	container.replaceChildren();
	for (const variant of variants) {
		const card = document.createElement("article"); card.className = "firmware-card"; card.dataset.variantId = variant.id;
		addText(card, "span", variant.status, "bench-badge status-badge"); addText(card, "span", "NO HARDWARE TESTING PERFORMED", "bench-badge hardware-badge");
		addText(card, "h3", variant.label); addText(card, "p", variant.description);
		const chips = document.createElement("div"); chips.className = "feature-chips"; variant.features.forEach((feature) => addText(chips, "span", feature)); card.append(chips);
		addText(card, "p", variant.caveat, "caveat");
		const facts = document.createElement("dl");
		[["Commit", variant.source.commit], ["Target", `${variant.target.environment} · ${variant.target.hardwareFamily} · ${variant.target.chip} · ${variant.target.board} · ${formatBytes(variant.target.flashSizeBytes)}`], ["Partition", `${variant.partition.scheme} · ${variant.partition.csv} · SHA-256 ${variant.partition.tableSha256}`], ["Transport", `${variant.transportAssumptions.usb}; ${variant.transportAssumptions.ota}`], ...variant.artifacts.map((artifact) => [artifact.transport.toUpperCase(), `${artifact.kind} · ${formatBytes(artifact.sizeBytes)} · SHA-256 ${artifact.sha256}`])].forEach(([term, value]) => { addText(facts, "dt", term); addText(facts, "dd", value); }); card.append(facts);
		for (const artifact of variant.artifacts) {
			const button = addText(card, "button", artifact.transport === "usb" ? "Download complete USB image" : "Download HTTP OTA app image", "firmware-action");
			button.type = "button";
			button.addEventListener("click", () => prepareFirmwareArtifact(variant, artifact, button));
			if (artifact.transport === "usb") {
				const browserCanFlash = canFlashLocally();
				const flashButton = addText(card, "button", browserCanFlash ? "Flash from this laptop" : "Open in Chrome to flash USB", "firmware-action laptop-flash");
				flashButton.type = "button";
				flashButton.disabled = !browserCanFlash;
				const flashStatus = addText(card, "p", browserCanFlash ? "Connects to USB on this laptop through Chrome/Edge." : "Safari cannot access USB serial devices. Open this same URL in desktop Chrome or Edge. Downloads still work here.", "local-flash-status");
				flashButton.addEventListener("click", () => runLaptopFlash(variant, artifact, flashButton, flashStatus));
			}
		}
		container.append(card);
	}
}

function renderFirmwareCards(manifest) {
	const artifacts = getHardwareArtifacts(manifest);
	appendFirmwareCards($("#firmwareCards"), artifacts);
	return artifacts;
}

async function runLaptopFlash(variant, artifact, button, status) {
	if (!window.confirm(`Flash ${variant.label} to the ESP connected to this laptop? This writes hardware and replaces its current firmware.`)) return;
	button.disabled = true;
	try {
		const result = await flashFromLaptop({
			variant,
			artifact,
			onStatus(message) { status.textContent = message; },
			onProgress(percent) { button.textContent = `Flashing… ${percent}%`; },
		});
		button.textContent = "Flashed — device reset";
		status.textContent = `${result.chipName} · ${formatBytes(result.bytesWritten)} · SHA-256 ${result.sha256.slice(0, 12)}…`;
	} catch (error) {
		button.textContent = "Flash from this laptop";
		status.textContent = error.name === "NotFoundError" ? "No USB device selected. Nothing was written." : `Flash stopped: ${error.message}`;
		button.disabled = false;
	}
}

async function prepareFirmwareArtifact(variant, artifact, button) {
	const wording = artifact.transport === "usb" ? "Prepare and download the complete merged USB image? This does not open USB or write hardware." : "Prepare and download the application-only HTTP OTA image? This does not contact a device or perform OTA.";
	if (!window.confirm(wording)) return;
	button.disabled = true;
	try {
		const response = await fetch(`/api/firmware/${encodeURIComponent(variant.id)}/${artifact.transport}`, { headers: { "X-Easy-Flash-Hardware-Family": variant.target.hardwareFamily, "X-Easy-Flash-Chip": variant.target.chip, "X-Easy-Flash-Flash-Bytes": String(variant.target.flashSizeBytes), "X-Easy-Flash-Partition-Sha256": variant.partition.tableSha256 } }); if (!response.ok) throw new Error("Unavailable");
		const link = document.createElement("a"); link.href = URL.createObjectURL(await response.blob()); link.download = artifact.transport === "usb" ? `${variant.id}-usb-merged.bin` : `${variant.id}-http-ota-app.bin`; link.click(); URL.revokeObjectURL(link.href);
		$("#firmwareOperationReceipt").textContent = JSON.stringify(makeFirmwareOperationReceipt(variant, artifact), null, 2); $("#firmwareOperationPanel").hidden = false; button.textContent = "Prepared/downloaded — not written";
	} catch { button.textContent = "Preparation failed safely"; button.disabled = false; }
}

async function initializeFirmwareBench() {
	try { const response = await fetch("/api/firmware-manifest"); if (!response.ok) throw new Error("Unavailable"); const manifest = await response.json(); const artifacts = renderFirmwareCards(manifest); const ota = artifacts[0]?.artifacts.find(({ transport }) => transport === "ota"); if (ota) discoveredArtifact = { status: "verified-manifest", releaseIdentity: artifacts[0].source.releaseIdentity || artifacts[0].label, sha256: ota.sha256 }; $("#firmwareManifestStatus").textContent = `${artifacts.length} verified hardware artifact · USB recovery + HTTP OTA`; }
	catch { $("#firmwareManifestStatus").textContent = "Firmware test bench unavailable. Participant Controller → Lights → Power → Review remains fully usable."; }
}
// AI: end

renderChoices($("#boardChoices"), catalog.boards, state.boardId, "board");
renderChoices($("#lightChoices"), catalog.lights, state.lightId, "light");
renderChoices($("#powerChoices"), catalog.power, state.powerId, "power");
initializeFirmwareBench();
document.querySelectorAll("[data-next],[data-go]").forEach((button) => button.addEventListener("click", () => showPanel(button.dataset.next || button.dataset.go)));
document.querySelectorAll("#stripType,#colorOrder,#pixels,#milliamps").forEach((input) => input.addEventListener("input", invalidateConfirmation));
$("#confirmed").addEventListener("change", (event) => $("#dryRun").disabled = !event.target.checked);
$("#connect").addEventListener("click", selectDevice);
$("#dryRun").addEventListener("click", completeDryRun);
$("#copy").addEventListener("click", async () => { await navigator.clipboard.writeText($("#receipt").textContent); $("#copy").textContent = "Copied"; });
$("#download").addEventListener("click", () => { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([$("#receipt").textContent], { type: "application/json" })); link.download = `wledtubes-dry-run-${new Date().toISOString().replaceAll(":", "-")}.json`; link.click(); URL.revokeObjectURL(link.href); });
// AI: end
