// AI: below section was generated by an AI
export function planMigration(source, target) {
	if (source.identityConfidence !== "exact" || !source.hardwareTargetId) {
		return { status: "blocked", reason: "An exact hardware identity is required before firmware selection.", steps: [] };
	}
	if (source.hardwareTargetId !== target.hardwareTargetId) {
		return { status: "blocked", reason: "The selected migration artifact does not match this hardware target.", steps: [] };
	}
	if (source.firmwareVariant && source.firmwareVariant !== "standard"
		&& (!source.variantMigrationProfileId
			|| source.variantMigrationProfileId !== target.runtimeProfileId)) {
		return { status: "blocked", reason: "A variant migration profile is required before replacing special legacy firmware.", steps: [] };
	}
	if (!((source.lineage === "stock-wled" && [14, 15, 16].includes(source.major))
		|| (source.lineage === "tubes" && [13, 14].includes(source.major)))) {
		return { status: "blocked", reason: "The installed firmware lineage is not in the pinned migration corpus.", steps: [] };
	}

	const steps = [{ operation: "backup-configuration" }];
	if (source.requiresExplicitBusBeforeFirmware) {
		steps.push({ operation: "normalize-hardware-output", scope: "explicit-led-bus-only" });
	}
	const alreadyOnTarget = source.lineage === "tubes"
		&& source.major === 14
		&& source.firmwareFixtureId === target.firmwareFixtureId;
	if (!alreadyOnTarget) {
		steps.push({ operation: "install-firmware", fixtureId: target.firmwareFixtureId });
	}
	steps.push({ operation: "verify-firmware", fixtureId: target.firmwareFixtureId });
	steps.push({
		operation: "apply-configuration",
		configurationSchema: target.configurationSchema,
		minimumVerifiedFirmwareFixtureId: target.firmwareFixtureId,
		runtimeProfileId: target.runtimeProfileId || null,
	});
	steps.push({ operation: "verify-configuration", configurationSchema: target.configurationSchema });
	return { status: "ready", steps };
}
// AI: end
