// AI: below section was generated by an AI
// The catalog keeps board, light, and power facts independent so a future CLI can resolve the same plan.
export const catalog = Object.freeze({
	boards: {
		dig2go: { id: "dig2go", name: "QuinLED Dig2Go", support: "Prototype supported", target: "esp32_quinled_dig2go_tubes", release: "DIG2GO_TUBES", gpio: 16, artifact: null },
		dignext2: { id: "dignext2", name: "QuinLED Dig-Next-2", support: "Coming later" },
		matrixM1: { id: "matrixM1", name: "ESP32-S3 Matrix M1", support: "Coming later" },
		athomC3: { id: "athomC3", name: "Athom ESP32-C3", support: "Coming later" },
		gledopto: { id: "gledopto", name: "Gledopto ESP32", support: "Coming later" }
	},
	lights: {
		referenceTube: { id: "referenceTube", name: "Steve-style 2 m tube", summary: "5 V SK6812, 30 logical pixels/m, paired front/back; RGBW/GRBW are prototype assumptions to confirm", type: "SK6812 RGBW (confirm)", order: "GRBW", pixels: 60, geometry: "Paired front/back; 60 logical addresses (120 physical packages)" },
		rgb: { id: "rgb", name: "Standard 5 V RGB strip", summary: "Common three-channel addressable strip", type: "WS2812B RGB", order: "GRB", pixels: 60, geometry: "One physical run" },
		rgbw: { id: "rgbw", name: "Standard 5 V RGBW strip", summary: "Common four-channel addressable strip", type: "SK6812 RGBW", order: "GRBW", pixels: 60, geometry: "One physical run" },
		custom: { id: "custom", name: "Custom / exact strip", summary: "Enter the bus facts yourself", type: "WS2812B RGB", order: "GRB", pixels: 60, geometry: "Custom" }
	},
	power: {
		low: { id: "low", name: "Low", milliamps: 500, note: "Conservative prototype example" },
		medium: { id: "medium", name: "Medium", milliamps: 1000, note: "Normal-supply prototype example" },
		high: { id: "high", name: "High", milliamps: 2000, note: "Prototype example; confirm supply, wiring, connector, controller, and strip" }
	}
});

// Resolves plain-language selections into an operation plan without performing device I/O.
export function resolveProfile(input) {
	const board = catalog.boards[input.boardId];
	const light = catalog.lights[input.lightId];
	const power = catalog.power[input.powerId];
	if (!board || !light || !power) throw new Error("Unknown profile selection");
	if (board.id !== "dig2go") throw new Error(`${board.name} is not supported by this prototype`);
	const pixels = Number(input.pixels ?? light.pixels);
	const milliamps = Number(input.milliamps ?? power.milliamps);
	const stripType = String(input.stripType || light.type).trim();
	const colorOrder = String(input.colorOrder || light.order).trim();
	if (!stripType || !colorOrder) throw new Error("Strip type and color order are required human-confirmed values");
	if (!Number.isInteger(pixels) || pixels < 1 || pixels > 2000) throw new Error("Logical pixel count must be from 1 to 2000");
	if (!Number.isInteger(milliamps) || milliamps < 100 || milliamps > 2000) throw new Error("This prototype limits current requests to 100–2000 mA; this is not an electrical safety certification");
	return {
		schemaVersion: 1,
		profile: { board: board.name, lights: light.name, power: power.name },
		hardwareArtifact: {
			targetId: board.id,
			environment: board.target,
			release: board.release
		},
		softwareProfile: {
			status: "waiting-for-split-protocol",
			requiresFirmware: false,
			note: "Art and behavior will be applied as runtime configuration when Steve's packet contract lands."
		},
		resolved: {
			firmwareTarget: board.target,
			firmwareRelease: board.release,
			gpio: board.gpio,
			stripType,
			colorOrder,
			logicalPixelCount: pixels,
			geometry: light.geometry,
			currentLimitMilliamps: milliamps
		},
		ownership: {
			firmware: ["Firmware target", "LED output GPIO"],
			wledRuntime: ["Strip type", "Color order", "Logical pixel count", "Hard current ceiling"],
			tubesRuntime: ["Geometry / product profile"]
		},
		artifact: board.artifact ? board.artifact : { status: "unavailable", identity: "No prebuilt artifact found in this checkout" },
		mode: "simulated-dry-run",
		warning: "The attached strip cannot be auto-detected. The operator must confirm its voltage, type, order, pixel count, wiring, and power limit."
	};
}

export function makeReceipt(plan, now = new Date(), artifact = null) {
	return { ...plan, artifact: artifact || plan.artifact, createdAt: now.toISOString(), result: "SIMULATED — no firmware written and no runtime settings applied" };
}
// AI: end
