import { createReadStream } from "node:fs";
import { stat } from "node:fs/promises";
import { createServer } from "node:http";
import { extname, join, normalize } from "node:path";
import { fileURLToPath } from "node:url";
import { loadFirmwareManifest, resolveFirmwareArtifact } from "./firmware-manifest.mjs";

const root = fileURLToPath(new URL("./", import.meta.url));
const port = Number(process.env.EASY_FLASH_PORT || 4173);
const types = { ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".mjs": "text/javascript; charset=utf-8", ".css": "text/css; charset=utf-8", ".svg": "image/svg+xml" };

// AI: below section was generated by an AI
// Serves only files inside the prototype directory and provides an offline-friendly local entry point.
export const server = createServer(async (request, response) => {
	const pathname = new URL(request.url, "http://localhost").pathname;
	if (pathname === "/api/firmware-manifest") {
		try {
			const manifest = await loadFirmwareManifest();
			response.writeHead(200, { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store" }).end(JSON.stringify(manifest));
		} catch {
			response.writeHead(503, { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store" }).end(JSON.stringify({ error: "Firmware manifest unavailable" }));
		}
		return;
	}
	if (pathname.startsWith("/api/firmware/")) {
		const match = pathname.match(/^\/api\/firmware\/([a-z0-9-]+)\/(usb|ota)$/);
		if (!match) { response.writeHead(404, { "Content-Type": "text/plain; charset=utf-8" }).end("Not found"); return; }
		try {
			const expectedTarget = request.headers["x-easy-flash-hardware-family"] ? { hardwareFamily: request.headers["x-easy-flash-hardware-family"], chip: request.headers["x-easy-flash-chip"], flashSizeBytes: Number(request.headers["x-easy-flash-flash-bytes"]), partitionTableSha256: request.headers["x-easy-flash-partition-sha256"] } : null;
			const { variant, artifact, absolutePath } = await resolveFirmwareArtifact(match[1], match[2], undefined, expectedTarget);
			const filename = `${variant.id}-${artifact.transport === "usb" ? "usb-merged" : "http-ota-app"}.bin`;
			response.writeHead(200, { "Content-Type": "application/octet-stream", "Content-Length": artifact.sizeBytes, "Content-Disposition": `attachment; filename="${filename}"`, "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff", "X-Easy-Flash-Hardware-Family": variant.target.hardwareFamily, "X-Easy-Flash-Chip": variant.target.chip, "X-Easy-Flash-Flash-Bytes": String(variant.target.flashSizeBytes), "X-Easy-Flash-Partition-Sha256": variant.partition.tableSha256 });
			createReadStream(absolutePath).pipe(response);
		} catch {
			response.writeHead(404, { "Content-Type": "text/plain; charset=utf-8", "Cache-Control": "no-store" }).end("Firmware artifact unavailable or failed integrity verification");
		}
		return;
	}

	const relative = pathname === "/" ? "index.html" : pathname.slice(1);
	const file = normalize(join(root, relative));
	if (!file.startsWith(root)) { response.writeHead(403).end("Forbidden"); return; }
	try {
		if (!(await stat(file)).isFile()) throw new Error("Not a file");
		response.writeHead(200, { "Content-Type": types[extname(file)] || "application/octet-stream", "Cache-Control": "no-store" });
		createReadStream(file).pipe(response);
	} catch {
		response.writeHead(404, { "Content-Type": "text/plain; charset=utf-8" }).end("Not found");
	}
});
// AI: end

if (process.argv[1] === fileURLToPath(import.meta.url)) server.listen(port, "127.0.0.1", () => console.log(`WLEDTubes Easy Flash: http://127.0.0.1:${port}`));
