#ifdef WAVESHARE_S3_TUBES_REMOTE

#include "wled.h"

#undef BLACK
#undef BLUE
#undef GREEN
#undef CYAN
#undef RED
#undef MAGENTA
#undef YELLOW
#undef WHITE
#undef ORANGE
#undef PURPLE
#undef DARKGREY

#include <Arduino_GFX_Library.h>
#include <SensorQMI8658.hpp>
#include <touch/TouchDrvCST92xx.h>
#include <XPowersLib.h>

#ifdef TUBES_S3_FIELD_OS
#include "../Tubes/s3_field_api.h"
#endif

// AI: below section was generated by an AI
namespace {
constexpr int8_t DISPLAY_CS = 12;
constexpr int8_t DISPLAY_SCLK = 38;
constexpr int8_t DISPLAY_SDIO0 = 4;
constexpr int8_t DISPLAY_SDIO1 = 5;
constexpr int8_t DISPLAY_SDIO2 = 6;
constexpr int8_t DISPLAY_SDIO3 = 7;
constexpr int8_t DISPLAY_RESET = 39;
constexpr int8_t PERIPHERAL_SDA = 15;
constexpr int8_t PERIPHERAL_SCL = 14;
constexpr int8_t TOUCH_IRQ = 11;
constexpr int8_t TOUCH_RESET = 40;
constexpr int16_t DISPLAY_WIDTH = 480;
constexpr int16_t DISPLAY_HEIGHT = 480;
constexpr uint32_t SAMPLE_INTERVAL_MS = 500;
constexpr uint32_t PREVIEW_INTERVAL_MS = 50;
constexpr uint8_t SMOKE_DEFAULT_BRIGHTNESS = 160;

volatile bool touchInterruptPending = false;

void IRAM_ATTR handleTouchInterrupt() {
  touchInterruptPending = true;
}

Arduino_ESP32QSPI displayBus(DISPLAY_CS, DISPLAY_SCLK, DISPLAY_SDIO0, DISPLAY_SDIO1,
                             DISPLAY_SDIO2, DISPLAY_SDIO3);
Arduino_CO5300 display(&displayBus, DISPLAY_RESET, 0, false, DISPLAY_WIDTH, DISPLAY_HEIGHT);
TouchDrvCST92xx touch;
SensorQMI8658 imu;
XPowersPMU pmu;

#ifdef TUBES_S3_FIELD_OS
enum class FieldScreen : uint8_t {
  Home,
  Conductor,
  Surveyor,
  Anchor,
  Updater
};

class WaveshareS3FieldOs : public Usermod {
private:
  bool displayReady = false;
  bool touchReady = false;
  FieldScreen screen = FieldScreen::Home;
  uint32_t lastPreviewDraw = 0;
  uint32_t lastTelemetryDraw = 0;
  uint32_t lastTouchActionMs = 0;
  static constexpr uint32_t TOUCH_DEBOUNCE_MS = 350;

  static constexpr uint16_t COLOR_BACKGROUND = 0x0863;
  static constexpr uint16_t COLOR_SURFACE = 0x10E7;
  static constexpr uint16_t COLOR_SURFACE_RAISED = 0x194A;
  static constexpr uint16_t COLOR_PRIMARY = 0x64FF;
  static constexpr uint16_t COLOR_MINT = 0x5F56;
  static constexpr uint16_t COLOR_AMBER = 0xFDC8;
  static constexpr uint16_t COLOR_MUTED = 0x8C51;

  static uint16_t rgb565(uint32_t color) {
    const uint8_t red = color >> 16;
    const uint8_t green = color >> 8;
    const uint8_t blue = color;
    return static_cast<uint16_t>(((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3));
  }

  void title(const __FlashStringHelper *text) {
    display.fillScreen(COLOR_BACKGROUND);
    display.setTextWrap(false);
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(24, 22);
    display.println(text);
  }

  void button(int16_t x, int16_t y, int16_t width, int16_t height, uint16_t color,
              const __FlashStringHelper *label) {
    display.fillRoundRect(x, y, width, height, 20, color);
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(x + 16, y + height / 2 - 8);
    display.println(label);
  }

  void drawHome() {
    title(F("Tubes Field OS"));
    display.setTextColor(COLOR_MUTED);
    display.setTextSize(1);
    display.setCursor(25, 51);
    display.println(F("The flock stays live wherever you go"));
    button(20, 84, 210, 164, COLOR_PRIMARY, F("Conductor"));
    button(250, 84, 210, 164, COLOR_MINT, F("Surveyor"));
    button(20, 268, 210, 164, 0xA23F, F("Anchor"));
    button(250, 268, 210, 164, COLOR_AMBER, F("Updater"));
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(1);
    display.setCursor(36, 199);
    display.println(F("Run the show"));
    display.setCursor(266, 199);
    display.println(F("Hear the field"));
    display.setCursor(36, 383);
    display.println(F("Shape proximity"));
    display.setCursor(266, 383);
    display.println(F("Service safely"));
  }

  void drawBack() {
    button(372, 12, 88, 48, COLOR_SURFACE_RAISED, F("Home"));
  }

  // Paints only the live viewport so animation never blanks the AMOLED.
  void drawConductorPreview(const TubesS3FieldStatus &status, bool drawFrame = false) {
    if (drawFrame) {
      display.fillRoundRect(20, 145, 440, 160, 24, COLOR_SURFACE);
      display.drawRoundRect(25, 150, 430, 150, 20, COLOR_SURFACE_RAISED);
    }
    for (size_t i = 0; i < TUBES_S3_PREVIEW_PIXELS; i++) {
      const int16_t x = 31 + static_cast<int16_t>(i * 7);
      display.fillRect(x, 156, 6, 138, rgb565(status.preview[i]));
    }
  }

  // Reports synchronization only when accepted state/beat traffic proves it.
  void drawConductorTelemetry(const TubesS3FieldStatus &status) {
    display.fillRect(20, 68, 440, 73, COLOR_BACKGROUND);
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(3);
    display.setCursor(22, 70);
    display.printf("%s\n", status.patternName);
    display.setTextColor(COLOR_MUTED);
    display.setTextSize(1);
    display.setCursor(24, 104);
    display.printf("%s  |  %u BPM  |  beat %u  |  %u peer%s\n",
                   status.isMaster ? "LEADING" : status.isFollowing ? "FOLLOWING" : "UNLINKED",
                   status.bpm, status.beat + 1, static_cast<unsigned>(status.peerCount),
                   status.peerCount == 1 ? "" : "s");
    display.setCursor(24, 123);
    display.setTextColor(COLOR_MUTED);
    display.printf("ID %03X  #%u", status.deviceId, status.deviceNumber);
    const uint32_t now = millis();
    if (!status.radioReady) {
      display.setTextColor(RGB565_RED);
      display.printf("Radio offline  |  channel %u\n", status.radioChannel);
    } else if (status.receivedPacketCount == 0) {
      display.setTextColor(COLOR_AMBER);
      display.printf("Listening on channel %u  |  no mesh packets heard\n", status.radioChannel);
    } else if (!status.isMaster && status.synchronizedPacketCount > 0 && now - status.lastSyncMs <= 20000) {
      display.setTextColor(COLOR_MINT);
      display.printf("SYNCED from %03X  |  RX %lums ago\n", status.syncSourceId, now - status.lastSyncMs);
    } else if (now - status.lastPacketMs > 20000) {
      display.setTextColor(COLOR_AMBER);
      display.printf("Mesh stale  |  last RX %lus ago\n", (now - status.lastPacketMs) / 1000);
    } else if (status.isMaster) {
      display.setTextColor(COLOR_MINT);
      display.printf("Mesh active  |  RX %lums  |  TX %lu packets\n",
                     now - status.lastPacketMs, status.transmittedPacketCount);
    } else {
      display.setTextColor(COLOR_AMBER);
      display.printf("Packets heard; no fresh sync state  |  RX %lums\n", now - status.lastPacketMs);
    }
  }

  void drawConductor() {
    TubesS3FieldStatus status;
    tubesS3ReadStatus(status);
    title(F("Conductor"));
    drawBack();
    drawConductorTelemetry(status);
    drawConductorPreview(status, true);
    button(20, 325, 210, 115, status.isMaster ? COLOR_PRIMARY : COLOR_SURFACE_RAISED, F("Next pattern"));
    button(250, 325, 210, 115, status.isMaster ? COLOR_SURFACE_RAISED : COLOR_MINT,
           status.isMaster ? F("Release master") : F("Become master"));
    lastPreviewDraw = millis();
    lastTelemetryDraw = millis();
  }

  void drawSurveyorTelemetry() {
    TubesS3FieldStatus status;
    tubesS3ReadStatus(status);
    display.fillRect(22, 72, 440, 54, COLOR_BACKGROUND);
    display.setTextSize(2);
    display.setCursor(24, 75);
    const uint32_t now = millis();
    if (!status.radioReady) {
      display.setTextColor(RGB565_RED);
      display.printf("RADIO OFFLINE  ch %u", status.radioChannel);
    } else if (status.receivedPacketCount == 0) {
      display.setTextColor(COLOR_AMBER);
      display.printf("LISTENING  ch %u", status.radioChannel);
    } else if (now - status.lastPacketMs > 20000) {
      display.setTextColor(COLOR_AMBER);
      display.printf("STALE  ch %u  %lus ago",
                     status.radioChannel, (now - status.lastPacketMs) / 1000);
    } else {
      display.setTextColor(COLOR_MINT);
      display.printf("ACTIVE  ch %u  RX %lums", status.radioChannel, now - status.lastPacketMs);
    }
    display.setTextColor(COLOR_MUTED);
    display.setTextSize(1);
    display.setCursor(24, 105);
    display.printf("%u peer%s  |  %lu packets  |  signal, not distance",
                   static_cast<unsigned>(status.peerCount), status.peerCount == 1 ? "" : "s",
                   status.receivedPacketCount);
    const size_t rows = status.peerCount < 8 ? status.peerCount : 8;
    for (size_t i = 0; i < 8; i++) {
      const int16_t y = 140 + static_cast<int16_t>(i * 38);
      display.fillRoundRect(22, y, 438, 30, 10, COLOR_SURFACE);
      if (i >= rows) continue;
      TubesS3PeerStatus peer;
      if (!tubesS3ReadPeer(i, peer)) continue;
      const uint32_t age = now - peer.lastSeenMs;
      display.setTextColor(age <= 20000 ? RGB565_WHITE : COLOR_MUTED);
      display.setTextSize(1);
      display.setCursor(34, y + 11);
      display.printf("%03X  via %03X   %4d dBm   %lus   %lu rx",
                     peer.nodeId, peer.uplinkId, peer.latestRssi, age / 1000, peer.samples);
    }
    if (rows == 0) {
      display.setTextColor(COLOR_MUTED);
      display.setTextSize(2);
      display.setCursor(42, 220);
      display.println(F("Waiting for Tubes..."));
    }
    lastTelemetryDraw = millis();
  }

  void drawSurveyor() {
    title(F("Surveyor"));
    drawBack();
    display.setTextColor(COLOR_MUTED);
    display.setTextSize(1);
    display.setCursor(24, 450);
    display.println(F("Live receiver evidence"));
    drawSurveyorTelemetry();
  }

  void drawAnchor() {
    TubesS3FieldStatus status;
    TubesS3RouteStatus route;
    tubesS3ReadStatus(status);
    tubesS3ReadRoute(route);
    title(F("Anchor"));
    drawBack();
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(24, 90);
    display.printf("Authority: %s\n", status.isMaster ? "MASTER" : "FOLLOWER");
    display.printf("Anchor: %s\n", route.anchorEnabled ? "ORIGINATING" : "OFF");
    if (route.routeValid) {
      display.printf("Shell %u  conductor %03X\n", route.shell, route.conductorId);
      display.printf("Parent %03X  cost %u\n", route.parentId, route.routeCost);
    } else {
      display.println(F("Shell unknown - no fresh route"));
    }
    display.setTextSize(1);
    display.setCursor(24, 245);
    display.println(F("Proximity route only; no location or ranging is claimed."));
    button(40, 325, 400, 100,
           route.anchorEnabled ? RGB565_RED : status.isMaster ? RGB565_PURPLE : RGB565_DARKGREY,
           route.anchorEnabled ? F("Disable anchor") : F("Enable anchor"));
  }

  void drawUpdater() {
    title(F("Updater"));
    drawBack();
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(24, 105);
    display.println(F("No approved firmware artifacts loaded."));
    display.setTextSize(1);
    display.setCursor(24, 175);
    display.println(F("P2P image transport is not integrated in this build."));
    display.println(F("No target can be selected, erased or updated here."));
    display.setTextColor(RGB565_YELLOW);
    display.setCursor(24, 255);
    display.println(F("Admission remains blocked until target identity,"));
    display.println(F("manifest, size and SHA-256 are all proven."));
  }

  void draw() {
    if (!displayReady) return;
    switch (screen) {
      case FieldScreen::Home: drawHome(); break;
      case FieldScreen::Conductor: drawConductor(); break;
      case FieldScreen::Surveyor: drawSurveyor(); break;
      case FieldScreen::Anchor: drawAnchor(); break;
      case FieldScreen::Updater: drawUpdater(); break;
    }
  }

  void onTouch(int16_t x, int16_t y) {
    const uint32_t now = millis();
    if (now - lastTouchActionMs < TOUCH_DEBOUNCE_MS) return;
    FieldScreen nextScreen = screen;
    bool action = false;
    if (screen != FieldScreen::Home && x >= 360 && y <= 75) {
      nextScreen = FieldScreen::Home;
      action = true;
    } else if (screen == FieldScreen::Home) {
      if (y >= 90 && y < 250) nextScreen = x < 240 ? FieldScreen::Conductor : FieldScreen::Surveyor;
      else if (y >= 250 && y < 430) nextScreen = x < 240 ? FieldScreen::Anchor : FieldScreen::Updater;
      action = nextScreen != screen;
    } else if (screen == FieldScreen::Conductor && y >= 325 && y < 440) {
      TubesS3FieldStatus status;
      tubesS3ReadStatus(status);
      if (x >= 20 && x < 230) tubesS3ForceNext();
      else if (x >= 250 && x < 460) tubesS3SetMasterAuthority(!status.isMaster);
      else return;
      action = true;
    } else if (screen == FieldScreen::Anchor && y >= 310) {
      TubesS3RouteStatus route;
      tubesS3ReadRoute(route);
      tubesS3SetAnchorAuthority(!route.anchorEnabled);
      action = true;
    }
    if (!action) return;
    lastTouchActionMs = now;
    if (nextScreen != screen) {
      screen = nextScreen;
      draw();
    } else if (screen == FieldScreen::Conductor) {
      TubesS3FieldStatus status;
      tubesS3ReadStatus(status);
      drawConductorTelemetry(status);
      drawConductorPreview(status, true);
    } else if (screen == FieldScreen::Anchor) {
      drawAnchor();
    }
  }

public:
  void setup() override {
    Wire.begin(PERIPHERAL_SDA, PERIPHERAL_SCL);
    displayReady = display.begin();
    if (displayReady) {
      display.setBrightness(SMOKE_DEFAULT_BRIGHTNESS);
      display.setTextWrap(false);
    }
    pinMode(TOUCH_RESET, OUTPUT);
    digitalWrite(TOUCH_RESET, LOW);
    delay(10);
    digitalWrite(TOUCH_RESET, HIGH);
    delay(50);
    pinMode(TOUCH_IRQ, INPUT_PULLUP);
    touchReady = touch.begin(Wire, CST92XX_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (touchReady) {
      touch.setMaxCoordinates(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      touchInterruptPending = false;
      attachInterrupt(TOUCH_IRQ, handleTouchInterrupt, FALLING);
    }
    draw();
  }

  void loop() override {
    if (touchReady && touchInterruptPending) {
      touchInterruptPending = false;
      int16_t x = -1;
      int16_t y = -1;
      if (touch.getPoint(&x, &y, 1) > 0) onTouch(x, y);
    }
    const uint32_t now = millis();
    if (displayReady && screen == FieldScreen::Conductor && now - lastPreviewDraw >= PREVIEW_INTERVAL_MS) {
      lastPreviewDraw = now;
      TubesS3FieldStatus status;
      tubesS3ReadStatus(status);
      drawConductorPreview(status);
    }
    if (displayReady && now - lastTelemetryDraw >= SAMPLE_INTERVAL_MS) {
      if (screen == FieldScreen::Conductor) {
        TubesS3FieldStatus status;
        tubesS3ReadStatus(status);
        drawConductorTelemetry(status);
        lastTelemetryDraw = now;
      } else if (screen == FieldScreen::Surveyor) {
        drawSurveyorTelemetry();
      }
    }
  }

  void addToJsonInfo(JsonObject &root) override {
    JsonObject user = root[F("u")];
    if (user.isNull()) user = root.createNestedObject(F("u"));
    JsonObject fieldOs = user.createNestedObject(F("S3 field OS"));
    fieldOs[F("display")] = displayReady ? F("OK") : F("FAIL");
    fieldOs[F("touch")] = touchReady ? F("OK") : F("FAIL");
#ifdef TUBES_S3_FIELD_OS
    TubesS3FieldStatus status;
    tubesS3ReadStatus(status);
    fieldOs[F("radio")] = status.radioReady;
    fieldOs[F("following")] = status.isFollowing;
    fieldOs[F("master")] = status.isMaster;
    fieldOs[F("peers")] = status.peerCount;
    fieldOs[F("rx")] = status.receivedPacketCount;
    fieldOs[F("sync")] = status.synchronizedPacketCount;
    fieldOs[F("lastSyncMs")] = status.lastSyncMs;
    fieldOs[F("lastRxMs")] = status.lastPacketMs;
    fieldOs[F("channel")] = status.radioChannel;
#endif
  }
};

static WaveshareS3FieldOs waveshareS3FieldOs;
REGISTER_USERMOD(waveshareS3FieldOs);
#else

class WaveshareS3PeripheralSmoke : public Usermod {
private:
  bool displayReady = false;
  bool touchReady = false;
  bool pmuReady = false;
  bool imuReady = false;
  uint8_t displayBrightness = SMOKE_DEFAULT_BRIGHTNESS;
  uint32_t lastSample = 0;
  int16_t touchX = -1;
  int16_t touchY = -1;
  uint16_t batteryMv = 0;
  bool usbPresent = false;
  bool charging = false;
  float accelX = 0.0f;
  float accelY = 0.0f;
  float accelZ = 0.0f;

  // Samples only board-local peripherals and never enters a Tubes transport path.
  void samplePeripherals() {
    if (pmuReady) {
      batteryMv = pmu.getBattVoltage();
      usbPresent = pmu.isVbusIn();
      charging = pmu.isCharging();
    }

    if (imuReady) imu.getAccelerometer(accelX, accelY, accelZ);

  }

  // Consumes the CST9217's falling-edge notification before its short IRQ pulse is lost.
  void sampleTouch() {
    if (!touchReady || !touchInterruptPending) return;
    touchInterruptPending = false;
    int16_t x = -1;
    int16_t y = -1;
    if (touch.getPoint(&x, &y, 1) > 0) {
      touchX = x;
      touchY = y;
    }
  }

  // Paints a stable diagnostic surface intended for first hardware bring-up.
  void drawStatus() {
    if (!displayReady) return;

    // Static frame is cleared only during setup; sampled values below repaint bounded rows.
    display.setCursor(12, 14);
    display.setTextColor(RGB565_CYAN);
    display.setTextSize(2);
    display.println(F("WLEDTubes S3 smoke"));
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(12, 62);
    display.print(F("Display  OK   BRI "));
    display.println(displayBrightness);
    display.setCursor(12, 104);
    display.print(F("Touch    "));
    display.print(touchReady ? F("OK") : F("FAIL"));
    display.print(F("   "));
    display.print(touchX);
    display.print(F(","));
    display.println(touchY);
    display.setCursor(12, 146);
    display.print(F("PMU      "));
    display.print(pmuReady ? F("OK") : F("FAIL"));
    display.print(F("   "));
    display.print(batteryMv);
    display.println(F(" mV"));
    display.setCursor(12, 188);
    display.print(F("USB      "));
    display.print(usbPresent ? F("YES") : F("NO"));
    display.print(F("   CHG "));
    display.println(charging ? F("YES") : F("NO"));
    display.setCursor(12, 230);
    display.print(F("IMU      "));
    display.println(imuReady ? F("OK") : F("FAIL"));
    display.setCursor(12, 272);
    display.print(F("ACC X "));
    display.println(accelX, 2);
    display.setCursor(12, 314);
    display.print(F("ACC Y "));
    display.println(accelY, 2);
    display.setCursor(12, 356);
    display.print(F("ACC Z "));
    display.println(accelZ, 2);
    display.setTextSize(1);
    display.setTextColor(RGB565_YELLOW);
    display.setCursor(12, 414);
    display.println(F("TOUCH: COORDINATES ONLY"));
    display.setCursor(12, 438);
    display.println(F("No LED output. No smoke-test radio TX."));
  }

public:
  void setup() override {
    Wire.begin(PERIPHERAL_SDA, PERIPHERAL_SCL);

    displayReady = display.begin();
    if (displayReady) {
      display.setBrightness(displayBrightness);
      display.setTextWrap(false);
    }

    pinMode(TOUCH_RESET, OUTPUT);
    digitalWrite(TOUCH_RESET, LOW);
    delay(10);
    digitalWrite(TOUCH_RESET, HIGH);
    delay(50);
    pinMode(TOUCH_IRQ, INPUT_PULLUP);
    touchReady = touch.begin(Wire, CST92XX_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (touchReady) {
      touch.setMaxCoordinates(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      touchInterruptPending = false;
      attachInterrupt(TOUCH_IRQ, handleTouchInterrupt, FALLING);
    }

    pmuReady = pmu.begin(Wire, AXP2101_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (pmuReady) {
      pmu.enableBattVoltageMeasure();
      pmu.enableVbusVoltageMeasure();
    }

    imuReady = imu.begin(Wire, QMI8658_L_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (imuReady) {
      imu.configAccelerometer(SensorQMI8658::ACC_RANGE_2G, SensorQMI8658::ACC_ODR_31_25Hz);
      imu.enableAccelerometer();
    }

    samplePeripherals();
    if (displayReady) display.fillScreen(RGB565_BLACK);
    drawStatus();
  }

  void loop() override {
    sampleTouch();
    const uint32_t now = millis();
    if (now - lastSample < SAMPLE_INTERVAL_MS) return;
    lastSample = now;
    samplePeripherals();
    drawStatus();
  }

  void addToJsonInfo(JsonObject &root) override {
    JsonObject user = root[F("u")];
    if (user.isNull()) user = root.createNestedObject(F("u"));
    JsonArray smoke = user.createNestedArray(F("S3 peripheral smoke"));
    smoke.add(displayReady ? F("display OK") : F("display FAIL"));
    smoke.add(touchReady ? F("touch OK") : F("touch FAIL"));
    smoke.add(pmuReady ? F("PMU OK") : F("PMU FAIL"));
    smoke.add(imuReady ? F("IMU OK") : F("IMU FAIL"));

    JsonArray battery = user.createNestedArray(F("S3 battery"));
    battery.add(batteryMv);
    battery.add(F(" mV"));
    JsonArray power = user.createNestedArray(F("S3 power"));
    power.add(usbPresent ? F("USB") : F("battery"));
    power.add(charging ? F(", charging") : F(""));
  }
};

static WaveshareS3PeripheralSmoke waveshareS3PeripheralSmoke;
REGISTER_USERMOD(waveshareS3PeripheralSmoke);
#endif
} // namespace

// Kept as a forced-link anchor for the board-specific PlatformIO environment.
extern "C" void waveshareS3PeripheralCompileCanary() {}
// AI: end

#endif
