#ifdef WAVESHARE_S3_TUBES_REMOTE

#include "wled.h"

#undef BLACK
#undef BLUE
#undef GREEN
#undef CYAN
#undef RED
#undef MAGENTA
#undef YELLOW
#undef WHITE
#undef ORANGE
#undef PURPLE
#undef DARKGREY

#include <Arduino_GFX_Library.h>
#include <SensorQMI8658.hpp>
#include <touch/TouchDrvCST92xx.h>
#include <XPowersLib.h>

#ifdef TUBES_S3_FIELD_OS
#include "../Tubes/s3_field_api.h"
#endif

// AI: below section was generated by an AI
namespace {
constexpr int8_t DISPLAY_CS = 12;
constexpr int8_t DISPLAY_SCLK = 38;
constexpr int8_t DISPLAY_SDIO0 = 4;
constexpr int8_t DISPLAY_SDIO1 = 5;
constexpr int8_t DISPLAY_SDIO2 = 6;
constexpr int8_t DISPLAY_SDIO3 = 7;
constexpr int8_t DISPLAY_RESET = 39;
constexpr int8_t PERIPHERAL_SDA = 15;
constexpr int8_t PERIPHERAL_SCL = 14;
constexpr int8_t TOUCH_IRQ = 11;
constexpr int8_t TOUCH_RESET = 40;
constexpr int16_t DISPLAY_WIDTH = 480;
constexpr int16_t DISPLAY_HEIGHT = 480;
constexpr uint32_t SAMPLE_INTERVAL_MS = 500;
constexpr uint8_t SMOKE_DEFAULT_BRIGHTNESS = 160;
constexpr uint8_t BRIGHTNESS_STEP = 32;

Arduino_ESP32QSPI displayBus(DISPLAY_CS, DISPLAY_SCLK, DISPLAY_SDIO0, DISPLAY_SDIO1,
                             DISPLAY_SDIO2, DISPLAY_SDIO3);
Arduino_CO5300 display(&displayBus, DISPLAY_RESET, 0, false, DISPLAY_WIDTH, DISPLAY_HEIGHT);
TouchDrvCST92xx touch;
SensorQMI8658 imu;
XPowersPMU pmu;

#ifdef TUBES_S3_FIELD_OS
enum class FieldScreen : uint8_t {
  Home,
  Conductor,
  Surveyor,
  Anchor,
  Updater
};

class WaveshareS3FieldOs : public Usermod {
private:
  bool displayReady = false;
  bool touchReady = false;
  bool touchLatched = false;
  FieldScreen screen = FieldScreen::Home;
  uint32_t lastDraw = 0;

  static uint16_t rgb565(uint32_t color) {
    const uint8_t red = color >> 16;
    const uint8_t green = color >> 8;
    const uint8_t blue = color;
    return static_cast<uint16_t>(((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3));
  }

  void title(const __FlashStringHelper *text) {
    display.fillScreen(RGB565_BLACK);
    display.setTextWrap(false);
    display.setTextColor(RGB565_CYAN);
    display.setTextSize(3);
    display.setCursor(20, 18);
    display.println(text);
  }

  void button(int16_t x, int16_t y, int16_t width, int16_t height, uint16_t color,
              const __FlashStringHelper *label) {
    display.fillRoundRect(x, y, width, height, 12, color);
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(x + 16, y + height / 2 - 8);
    display.println(label);
  }

  void drawHome() {
    title(F("Tubes Field OS"));
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(1);
    display.setCursor(22, 55);
    display.println(F("Mesh, clock and art stay live on every screen"));
    button(20, 90, 210, 150, RGB565_BLUE, F("Conductor"));
    button(250, 90, 210, 150, RGB565_DARKGREEN, F("Surveyor"));
    button(20, 260, 210, 150, RGB565_PURPLE, F("Anchor"));
    button(250, 260, 210, 150, RGB565_ORANGE, F("Updater"));
  }

  void drawBack() {
    button(370, 15, 90, 45, RGB565_DARKGREY, F("Home"));
  }

  void drawConductor() {
    TubesS3FieldStatus status;
    tubesS3ReadStatus(status);
    title(F("Conductor"));
    drawBack();
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(22, 78);
    display.printf("%s  Role %u\n", status.isMaster ? "MASTER" : "FOLLOWER", status.role);
    display.printf("Pattern %u   Palette %u\n", status.patternId, status.paletteId);
    display.printf("Tempo %u BPM   Beat %u\n", status.bpm, status.beat + 1);
    display.printf("Peers heard %u\n", static_cast<unsigned>(status.peerCount));

    for (size_t i = 0; i < TUBES_S3_PREVIEW_PIXELS; i++) {
      display.fillRect(20 + i * 37, 190, 32, 110, rgb565(status.preview[i]));
    }
    button(20, 335, 210, 100, status.isMaster ? RGB565_BLUE : RGB565_DARKGREY, F("Next"));
    button(250, 335, 210, 100, status.isMaster ? RGB565_DARKGREEN : RGB565_RED,
           status.isMaster ? F("Release master") : F("Become master"));
  }

  void drawSurveyor() {
    TubesS3FieldStatus status;
    tubesS3ReadStatus(status);
    title(F("Surveyor"));
    drawBack();
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(1);
    display.setCursor(22, 72);
    display.printf("Recently heard peers: %u   RSSI is observed signal strength\n\n",
                   static_cast<unsigned>(status.peerCount));
    const size_t rows = status.peerCount < 9 ? status.peerCount : 9;
    for (size_t i = 0; i < rows; i++) {
      TubesS3PeerStatus peer;
      if (!tubesS3ReadPeer(i, peer)) continue;
      display.printf("%03X via %03X   %4d dBm   min %4d max %4d   %lus\n",
                     peer.nodeId, peer.uplinkId, peer.latestRssi, peer.minimumRssi,
                     peer.maximumRssi, (millis() - peer.lastSeenMs) / 1000);
    }
    if (rows == 0) display.println(F("No Tubes packets heard yet."));
    display.setCursor(22, 430);
    display.setTextColor(RGB565_YELLOW);
    display.println(F("No distance or position is inferred from RSSI."));
  }

  void drawAnchor() {
    title(F("Anchor"));
    drawBack();
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(24, 105);
    display.println(F("Spatial anchor controls are not enabled yet."));
    display.setTextSize(1);
    display.setCursor(24, 175);
    display.println(F("The current firmware has no trusted coordinates or ranging."));
    display.println(F("This screen will expose proximity-anchor state only after"));
    display.println(F("the existing mobile-conductor sidecar is integrated."));
  }

  void drawUpdater() {
    title(F("Updater"));
    drawBack();
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(24, 105);
    display.println(F("No approved firmware artifacts loaded."));
    display.setTextSize(1);
    display.setCursor(24, 175);
    display.println(F("P2P image transport is not integrated in this build."));
    display.println(F("No target can be selected, erased or updated here."));
    display.setTextColor(RGB565_YELLOW);
    display.setCursor(24, 255);
    display.println(F("Admission remains blocked until target identity,"));
    display.println(F("manifest, size and SHA-256 are all proven."));
  }

  void draw() {
    if (!displayReady) return;
    switch (screen) {
      case FieldScreen::Home: drawHome(); break;
      case FieldScreen::Conductor: drawConductor(); break;
      case FieldScreen::Surveyor: drawSurveyor(); break;
      case FieldScreen::Anchor: drawAnchor(); break;
      case FieldScreen::Updater: drawUpdater(); break;
    }
  }

  void onTouch(int16_t x, int16_t y) {
    if (screen != FieldScreen::Home && x >= 360 && y <= 75) {
      screen = FieldScreen::Home;
    } else if (screen == FieldScreen::Home) {
      if (y >= 90 && y < 250) screen = x < 240 ? FieldScreen::Conductor : FieldScreen::Surveyor;
      else if (y >= 250 && y < 430) screen = x < 240 ? FieldScreen::Anchor : FieldScreen::Updater;
    } else if (screen == FieldScreen::Conductor && y >= 320) {
      TubesS3FieldStatus status;
      tubesS3ReadStatus(status);
      if (x < 240) tubesS3ForceNext();
      else tubesS3SetMasterAuthority(!status.isMaster);
    }
    draw();
    lastDraw = millis();
  }

public:
  void setup() override {
    Wire.begin(PERIPHERAL_SDA, PERIPHERAL_SCL);
    displayReady = display.begin();
    if (displayReady) {
      display.setBrightness(SMOKE_DEFAULT_BRIGHTNESS);
      display.setTextWrap(false);
    }
    pinMode(TOUCH_RESET, OUTPUT);
    digitalWrite(TOUCH_RESET, LOW);
    delay(10);
    digitalWrite(TOUCH_RESET, HIGH);
    delay(50);
    pinMode(TOUCH_IRQ, INPUT_PULLUP);
    touchReady = touch.begin(Wire, CST92XX_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (touchReady) touch.setMaxCoordinates(DISPLAY_WIDTH, DISPLAY_HEIGHT);
    draw();
  }

  void loop() override {
    if (touchReady) {
      int16_t x = -1;
      int16_t y = -1;
      const bool pressed = digitalRead(TOUCH_IRQ) == LOW && touch.getPoint(&x, &y, 1) > 0;
      if (pressed && !touchLatched) onTouch(x, y);
      touchLatched = pressed;
    }
    const uint32_t now = millis();
    if (now - lastDraw >= SAMPLE_INTERVAL_MS) {
      lastDraw = now;
      draw();
    }
  }

  void addToJsonInfo(JsonObject &root) override {
    JsonObject user = root[F("u")];
    if (user.isNull()) user = root.createNestedObject(F("u"));
    JsonArray fieldOs = user.createNestedArray(F("S3 field OS"));
    fieldOs.add(displayReady ? F("display OK") : F("display FAIL"));
    fieldOs.add(touchReady ? F("touch OK") : F("touch FAIL"));
  }
};

static WaveshareS3FieldOs waveshareS3FieldOs;
REGISTER_USERMOD(waveshareS3FieldOs);
#else

class WaveshareS3PeripheralSmoke : public Usermod {
private:
  bool displayReady = false;
  bool touchReady = false;
  bool pmuReady = false;
  bool imuReady = false;
  bool touchLatched = false;
  uint8_t displayBrightness = SMOKE_DEFAULT_BRIGHTNESS;
  uint32_t lastSample = 0;
  int16_t touchX = -1;
  int16_t touchY = -1;
  uint16_t batteryMv = 0;
  bool usbPresent = false;
  bool charging = false;
  float accelX = 0.0f;
  float accelY = 0.0f;
  float accelZ = 0.0f;

  // Samples only board-local peripherals and never enters a Tubes transport path.
  void samplePeripherals() {
    if (pmuReady) {
      batteryMv = pmu.getBattVoltage();
      usbPresent = pmu.isVbusIn();
      charging = pmu.isCharging();
    }

    if (imuReady) imu.getAccelerometer(accelX, accelY, accelZ);

    if (!touchReady) return;
    int16_t x = -1;
    int16_t y = -1;
    const bool pressed = digitalRead(TOUCH_IRQ) == LOW && touch.getPoint(&x, &y, 1) > 0;
    if (pressed) {
      touchX = x;
      touchY = y;
      if (!touchLatched) {
        if (x < DISPLAY_WIDTH / 2 && displayBrightness > BRIGHTNESS_STEP) {
          displayBrightness -= BRIGHTNESS_STEP;
        } else if (x >= DISPLAY_WIDTH / 2 && displayBrightness < 255 - BRIGHTNESS_STEP) {
          displayBrightness += BRIGHTNESS_STEP;
        } else {
          displayBrightness = x < DISPLAY_WIDTH / 2 ? 1 : 255;
        }
        if (displayReady) display.setBrightness(displayBrightness);
      }
    }
    touchLatched = pressed;
  }

  // Paints a stable diagnostic surface intended for first hardware bring-up.
  void drawStatus() {
    if (!displayReady) return;

    display.fillScreen(RGB565_BLACK);
    display.setCursor(12, 14);
    display.setTextColor(RGB565_CYAN);
    display.setTextSize(2);
    display.println(F("WLEDTubes S3 smoke"));
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(1);
    display.printf("%s\n%s\nBuilt %s %s\n\n", releaseString, versionString, __DATE__, __TIME__);
    display.printf("Display: OK  brightness %u\n", displayBrightness);
    display.printf("Touch:   %s  x %d  y %d\n", touchReady ? "OK" : "FAIL", touchX, touchY);
    display.printf("PMU:     %s  battery %u mV\n", pmuReady ? "OK" : "FAIL", batteryMv);
    display.printf("USB:     %s  charge %s\n", usbPresent ? "YES" : "NO", charging ? "YES" : "NO");
    display.printf("IMU:     %s\n", imuReady ? "OK" : "FAIL");
    display.printf("Accel:   %+.2f  %+.2f  %+.2f g\n\n", accelX, accelY, accelZ);
    display.setTextColor(RGB565_YELLOW);
    display.println(F("Touch left/right: brightness -/+"));
    display.println(F("No LED output. No smoke-test radio TX."));
  }

public:
  void setup() override {
    Wire.begin(PERIPHERAL_SDA, PERIPHERAL_SCL);

    displayReady = display.begin();
    if (displayReady) {
      display.setBrightness(displayBrightness);
      display.setTextWrap(false);
    }

    pinMode(TOUCH_RESET, OUTPUT);
    digitalWrite(TOUCH_RESET, LOW);
    delay(10);
    digitalWrite(TOUCH_RESET, HIGH);
    delay(50);
    pinMode(TOUCH_IRQ, INPUT_PULLUP);
    touchReady = touch.begin(Wire, CST92XX_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (touchReady) touch.setMaxCoordinates(DISPLAY_WIDTH, DISPLAY_HEIGHT);

    pmuReady = pmu.begin(Wire, AXP2101_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (pmuReady) {
      pmu.enableBattVoltageMeasure();
      pmu.enableVbusVoltageMeasure();
    }

    imuReady = imu.begin(Wire, QMI8658_L_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (imuReady) {
      imu.configAccelerometer(SensorQMI8658::ACC_RANGE_2G, SensorQMI8658::ACC_ODR_31_25Hz);
      imu.enableAccelerometer();
    }

    samplePeripherals();
    drawStatus();
  }

  void loop() override {
    const uint32_t now = millis();
    if (now - lastSample < SAMPLE_INTERVAL_MS) return;
    lastSample = now;
    samplePeripherals();
    drawStatus();
  }

  void addToJsonInfo(JsonObject &root) override {
    JsonObject user = root[F("u")];
    if (user.isNull()) user = root.createNestedObject(F("u"));
    JsonArray smoke = user.createNestedArray(F("S3 peripheral smoke"));
    smoke.add(displayReady ? F("display OK") : F("display FAIL"));
    smoke.add(touchReady ? F("touch OK") : F("touch FAIL"));
    smoke.add(pmuReady ? F("PMU OK") : F("PMU FAIL"));
    smoke.add(imuReady ? F("IMU OK") : F("IMU FAIL"));

    JsonArray battery = user.createNestedArray(F("S3 battery"));
    battery.add(batteryMv);
    battery.add(F(" mV"));
    JsonArray power = user.createNestedArray(F("S3 power"));
    power.add(usbPresent ? F("USB") : F("battery"));
    power.add(charging ? F(", charging") : F(""));
  }
};

static WaveshareS3PeripheralSmoke waveshareS3PeripheralSmoke;
REGISTER_USERMOD(waveshareS3PeripheralSmoke);
#endif
} // namespace

// Kept as a forced-link anchor for the board-specific PlatformIO environment.
extern "C" void waveshareS3PeripheralCompileCanary() {}
// AI: end

#endif
