#include <array>
#include <cstdint>
#include <iostream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include "firmware_http_source.h"

// AI: below section was generated by an AI
namespace {

void expect(bool condition, const std::string& message) {
  if (!condition)
    throw std::runtime_error(message);
}

FirmwareImageArtifact artifactFor(size_t imageLength) {
  FirmwareImageArtifact artifact;
  artifact.imageLengthBytes = imageLength;
  artifact.releaseHash = 0x12345678;
  return artifact;
}

std::vector<uint8_t> drain(FirmwareHttpSource& response, size_t chunkSize) {
  std::vector<uint8_t> bytes;
  std::vector<uint8_t> chunk(chunkSize);
  while (!response.complete()) {
    const size_t count = response.read(chunk.data(), chunk.size());
    expect(count > 0, "response stalled before completion");
    bytes.insert(bytes.end(), chunk.begin(), chunk.begin() + count);
  }
  return bytes;
}

void full_get_streams_exact_artifact() {
  const uint8_t image[] = {1, 2, 3, 4, 5, 6};
  MemoryFirmwareImageSource source(image, sizeof(image), artifactFor(sizeof(image)));
  FirmwareHttpSource response(source);

  expect(response.begin(FirmwareHttpMethodGet, nullptr), "full GET was rejected");
  expect(response.status() == 200, "full GET did not return 200");
  expect(response.artifact().releaseHash == 0x12345678, "artifact identity was lost");
  expect(response.imageLength() == sizeof(image), "full image length changed");
  expect(response.contentOffset() == 0, "full GET offset changed");
  expect(response.contentLength() == sizeof(image), "full GET length changed");
  expect(drain(response, 2) == std::vector<uint8_t>(image, image + sizeof(image)),
      "full GET returned wrong bytes");
}

void bounded_range_returns_partial_content() {
  const uint8_t image[] = {10, 20, 30, 40, 50, 60};
  MemoryFirmwareImageSource source(image, sizeof(image), artifactFor(sizeof(image)));
  FirmwareHttpSource response(source);

  expect(response.begin(FirmwareHttpMethodGet, "bytes=2-4"), "valid range was rejected");
  expect(response.status() == 206, "range GET did not return 206");
  expect(response.contentOffset() == 2, "range offset changed");
  expect(response.contentLength() == 3, "range length changed");
  expect(drain(response, 8) == std::vector<uint8_t>({30, 40, 50}),
      "range GET returned wrong bytes");

  expect(response.begin(FirmwareHttpMethodGet, "bytes=4-"), "open range was rejected");
  expect(response.imageLength() == sizeof(image), "range lost full image length");
  expect(drain(response, 1) == std::vector<uint8_t>({50, 60}),
      "open range returned wrong bytes");
}

void head_reports_without_reading_source() {
  const uint8_t image[] = {7, 8, 9};
  MemoryFirmwareImageSource source(image, sizeof(image), artifactFor(sizeof(image)));
  FirmwareHttpSource response(source);

  expect(response.begin(FirmwareHttpMethodHead, nullptr), "HEAD was rejected");
  expect(response.status() == 200, "HEAD did not return 200");
  expect(response.contentLength() == sizeof(image), "HEAD length changed");
  expect(response.complete(), "HEAD expected a response body");
}

void malformed_or_unbounded_ranges_fail_closed() {
  const uint8_t image[] = {1, 2, 3, 4};
  MemoryFirmwareImageSource source(image, sizeof(image), artifactFor(sizeof(image)));
  FirmwareHttpSource response(source);

  expect(!response.begin(FirmwareHttpMethodGet, "bytes=3-9"), "past-end range succeeded");
  expect(response.status() == 416, "past-end range did not return 416");
  expect(!response.begin(FirmwareHttpMethodGet, "bytes=0-1,2-3"), "multi-range succeeded");
  expect(response.status() == 416, "multi-range did not return 416");
  expect(!response.begin(FirmwareHttpMethodGet, "items=0-1"), "wrong range unit succeeded");
  expect(response.status() == 416, "wrong range unit did not return 416");
  expect(!response.begin(FirmwareHttpMethodGet, "bytes=184467440737095516160-1"),
      "overflowing range succeeded");
  expect(response.status() == 416, "overflowing range did not return 416");
}

void source_inspection_failure_is_unavailable() {
  const uint8_t image[] = {1, 2};
  MemoryFirmwareImageSource source(image, sizeof(image), artifactFor(sizeof(image) + 1));
  FirmwareHttpSource response(source);

  expect(!response.begin(FirmwareHttpMethodGet, nullptr), "invalid source was served");
  expect(response.status() == 503, "invalid source did not return 503");
  uint8_t output = 0;
  expect(response.read(&output, 1) == 0, "invalid source returned bytes");
}

} // namespace

int main() {
  const std::array<std::pair<const char*, void (*)()>, 5> tests = {{
    {"full GET streams exact artifact", full_get_streams_exact_artifact},
    {"bounded range returns partial content", bounded_range_returns_partial_content},
    {"HEAD reports without reading source", head_reports_without_reading_source},
    {"malformed or unbounded ranges fail closed", malformed_or_unbounded_ranges_fail_closed},
    {"source inspection failure is unavailable", source_inspection_failure_is_unavailable},
  }};

  for (const auto& test : tests) {
    try {
      test.second();
      std::cout << "PASS: " << test.first << '\n';
    } catch (const std::exception& error) {
      std::cerr << "FAIL: " << test.first << ": " << error.what() << '\n';
      return 1;
    }
  }
  return 0;
}
// AI: end
