#include <array>
#include <cstdio>
#include <cstdint>
#include <iostream>
#include <stdexcept>
#include <string>
#include <utility>

#include "firmware_image_source.h"

// AI: below section was generated by an AI
namespace {

void expect(bool condition, const std::string& message) {
  if (!condition)
    throw std::runtime_error(message);
}

FirmwareImageArtifact artifactFor(size_t imageLength) {
  FirmwareImageArtifact artifact;
  artifact.imageLengthBytes = imageLength;
  artifact.releaseHash = 0x12345678;
  return artifact;
}

void memory_source_is_bounded_and_read_only() {
  const uint8_t bytes[] = {10, 20, 30, 40, 50};
  MemoryFirmwareImageSource source(bytes, sizeof(bytes), artifactFor(sizeof(bytes)));
  FirmwareImageArtifact artifact;
  expect(source.inspect(artifact), "valid memory artifact failed inspection");
  expect(artifact.imageLengthBytes == sizeof(bytes), "memory artifact length changed");

  uint8_t output[2] = {0};
  expect(source.read(2, output, sizeof(output)), "bounded memory read failed");
  expect(output[0] == 30 && output[1] == 40, "memory read returned wrong bytes");
  expect(!source.read(4, output, sizeof(output)), "past-end memory read succeeded");
  expect(!source.read(0, nullptr, 1), "null memory destination succeeded");
}

void metadata_cannot_expand_memory_source() {
  const uint8_t bytes[] = {1, 2, 3};
  MemoryFirmwareImageSource source(bytes, sizeof(bytes), artifactFor(sizeof(bytes) + 1));
  FirmwareImageArtifact artifact;
  expect(!source.inspect(artifact), "oversized memory metadata was admitted");
}

void file_source_rejects_metadata_length_mismatch() {
  FILE* file = tmpfile();
  expect(file != nullptr, "temporary file could not be opened");
  const uint8_t bytes[] = {5, 6, 7, 8};
  expect(fwrite(bytes, 1, sizeof(bytes), file) == sizeof(bytes), "fixture write failed");
  expect(fflush(file) == 0, "fixture flush failed");

  FileFirmwareImageSource wrongLength(file, artifactFor(sizeof(bytes) + 1));
  FirmwareImageArtifact artifact;
  expect(!wrongLength.inspect(artifact), "wrong file length was admitted");

  FileFirmwareImageSource source(file, artifactFor(sizeof(bytes)));
  expect(source.inspect(artifact), "valid file artifact failed inspection");
  uint8_t output[2] = {0};
  expect(source.read(1, output, sizeof(output)), "bounded file read failed");
  expect(output[0] == 6 && output[1] == 7, "file read returned wrong bytes");
  expect(!source.read(3, output, sizeof(output)), "past-end file read succeeded");
  fclose(file);
}

} // namespace

int main() {
  const std::array<std::pair<const char*, void (*)()>, 3> tests = {{
    {"memory source is bounded and read only", memory_source_is_bounded_and_read_only},
    {"metadata cannot expand memory source", metadata_cannot_expand_memory_source},
    {"file source rejects metadata length mismatch", file_source_rejects_metadata_length_mismatch},
  }};

  for (const auto& test : tests) {
    try {
      test.second();
      std::cout << "PASS: " << test.first << '\n';
    } catch (const std::exception& error) {
      std::cerr << "FAIL: " << test.first << ": " << error.what() << '\n';
      return 1;
    }
  }
  return 0;
}
// AI: end
