#!/usr/bin/env python3
"""Build, validate, embed, and size-check the current S3 carrier."""

from __future__ import annotations

import argparse
import importlib.util
import pathlib
import re
import shutil
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
VAULT = REPO / "build_output" / "s3_vault"
FIRMWARE = REPO / "build_output" / "firmware"
OTA_SLOT = 0x600000
REQUIRED_HEADROOM = 0x40000
PROFILES = (
    ("esp32_quinled_dig2go_tubes_p2p_v48",
     "esp32_quinled_dig2go_tubes_p2p_v48.bin", "dig2go"),
    ("esp32-c3-athom_tubes_v48", "esp32-c3-athom_tubes_v48.bin", "athom-c3"),
)
CARRIER_RELEASE = 48


def current_release() -> int:
    source = (REPO / "usermods" / "Tubes" / "updater.h").read_text(encoding="utf-8")
    match = re.search(r"^#define RELEASE_VERSION\s+(\d+)\s*$", source, re.MULTILINE)
    if not match:
        raise SystemExit("could not read RELEASE_VERSION from usermods/Tubes/updater.h")
    return int(match.group(1))


def run(*command: str) -> None:
    subprocess.run(command, cwd=REPO, check=True)


def load_validator():
    path = REPO / "tools" / "validate_s3_vault_artifacts.py"
    spec = importlib.util.spec_from_file_location("validate_s3_vault_artifacts", path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def write_header(artifacts, release: int) -> None:
    by_profile = {artifact.profile: artifact for artifact in artifacts}
    dig2go = by_profile["dig2go"]
    c3 = by_profile["athom-c3"]
    header = (
        "#pragma once\n"
        "// Generated by tools/build_s3_carrier.py; do not edit.\n"
        f"#define S3_VAULT_RELEASE {release}\n"
        f"#define S3_VAULT_DIG2GO_SIZE {dig2go.size}U\n"
        f"#define S3_VAULT_DIG2GO_MD5 \"{dig2go.md5}\"\n"
        f"#define S3_VAULT_ATHOM_C3_SIZE {c3.size}U\n"
        f"#define S3_VAULT_ATHOM_C3_MD5 \"{c3.md5}\"\n"
    )
    (VAULT / "s3_vault_artifacts.h").write_text(header, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pio", default="pio")
    parser.add_argument("--skip-payload-build", action="store_true")
    args = parser.parse_args()
    release = CARRIER_RELEASE
    VAULT.mkdir(parents=True, exist_ok=True)
    if not args.skip_payload_build:
        for environment, _, _ in PROFILES:
            run(args.pio, "run", "-e", environment)

    validator = load_validator()
    artifacts = []
    for _, filename, profile in PROFILES:
        source = FIRMWARE / filename
        if not source.is_file():
            raise SystemExit(f"missing payload artifact: {source}")
        destination = VAULT / filename
        shutil.copyfile(source, destination)
        artifacts.append(validator.inspect(profile, destination, release))
    write_header(artifacts, release)

    run(args.pio, "run", "-e", "waveshare_s3_tubes_carrier")
    s3_image = FIRMWARE / "waveshare_s3_tubes_carrier.bin"
    if not s3_image.is_file():
        raise SystemExit(f"missing S3 carrier image: {s3_image}")
    maximum = OTA_SLOT - REQUIRED_HEADROOM
    if s3_image.stat().st_size > maximum:
        raise SystemExit(
            f"S3 carrier is {s3_image.stat().st_size} bytes; maximum with required "
            f"headroom is {maximum} bytes"
        )
    print(f"S3 carrier: {s3_image} ({s3_image.stat().st_size} bytes, "
          f"{OTA_SLOT - s3_image.stat().st_size} bytes slot headroom)")


if __name__ == "__main__":
    main()
