#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <set>

#include "../usermods/Tubes/fleet_update_protocol.h"

// AI: below section was generated by an AI

static void require(bool condition, const char* message) {
  if (condition)
    return;
  fprintf(stderr, "%s\n", message);
  exit(1);
}

static FleetUpdateOffer validOffer() {
  FleetUpdateOffer offer;
  offer.tubesVersion = 22;
  offer.nonce = 0x89ABCDEF;
  offer.serverAddress[0] = 192;
  offer.serverAddress[1] = 168;
  offer.serverAddress[2] = 0;
  offer.serverAddress[3] = 101;
  offer.serverPort = 8080;
  offer.startWindowMs = 5000;
  return offer;
}

int main() {
  // A complete offer is accepted and its wildcard reaches every nonzero Device ID.
  FleetUpdateOffer offer = validOffer();
  require(isValidFleetUpdateOffer(offer), "valid offer was rejected");
  require(fleetUpdateTargetsDevice(offer, 0x1234), "wildcard offer did not target a device");
  offer.targetDeviceId = 0x1234;
  require(fleetUpdateTargetsDevice(offer, 0x1234), "exact target was rejected");
  require(!fleetUpdateTargetsDevice(offer, 0x1235), "different Device ID accepted a targeted offer");

  // Unknown flags and oversized credentials fail closed so later protocols or
  // truncated secrets cannot be misread as this version's authorization.
  FleetUpdateOffer invalid = validOffer();
  invalid.flags = 0x80;
  require(!isValidFleetUpdateOffer(invalid), "unknown flag was accepted");
  invalid = validOffer();
  invalid.ssidLength = FLEET_UPDATE_CREDENTIAL_BYTES;
  invalid.passwordLength = 1;
  require(!isValidFleetUpdateOffer(invalid), "oversized credentials were accepted");
  invalid = validOffer();
  invalid.startWindowMs = FLEET_UPDATE_MAX_START_WINDOW_MS + 1;
  require(!isValidFleetUpdateOffer(invalid), "oversized start window was accepted");
  offer = validOffer();
  require(setFleetUpdateCredentials(offer, "Eisner", "test-password"), "bounded credentials were rejected");
  require(isValidFleetUpdateOffer(offer), "offer with bounded credentials was rejected");

  // Fifty stable MACs spread throughout the requested window without any fleet
  // roster or coordinator state on the devices.
  offer = validOffer();
  std::set<uint16_t> delays;
  for (uint8_t device = 0; device < 50; device++) {
    uint8_t mac[6] = {0x02, 0, 0, 0, 0, device};
    uint16_t delay = fleetUpdateStartDelay(offer, mac);
    require(delay <= offer.startWindowMs, "scheduled delay exceeded the offer window");
    delays.insert(delay);
  }
  require(delays.size() >= 45, "stable scheduling clustered fifty devices too tightly");

  // The proven P2P seed is an exact-target, equal-release serve command with
  // no OTA server, credentials, wildcard, or force flag.
  FleetUpdateOffer propagation;
  require(makeModernPropagationServeCommand(
      propagation, 47, 0x10203040, 0x1234),
      "exact propagation command was rejected");
  require(propagation.flags == FleetUpdatePropagate,
      "propagation command lost explicit opt-in");
  require(propagation.tubesVersion == 47 && propagation.targetDeviceId == 0x1234,
      "propagation command lost artifact or target identity");
  require(propagation.serverPort == 0 && propagation.ssidLength == 0
      && propagation.passwordLength == 0,
      "propagation command invented OTA transport or credentials");
  propagation.targetDeviceId = 0;
  require(!isValidFleetUpdateOffer(propagation),
      "wildcard serve-current propagation was accepted");

  printf("fleet update protocol scenarios passed\n");
  return 0;
}

// AI: end
