#include <assert.h>
#include <stdint.h>

#include "usermods/Tubes/peer_telemetry.h"

// AI: below section was generated by an AI
// Proves bounded peer tracking, RSSI summaries, saturation, and oldest-entry replacement.
int main() {
  PeerTelemetry telemetry;
  telemetry.observe(0, 1, -50, 10);
  telemetry.observe(1, 0, 0, 10);
  assert(telemetry.count() == 1);
  const PeerTelemetryEntry *unknownRssi = telemetry.get(1);
  assert(unknownRssi != nullptr);
  assert(unknownRssi->samples == 1);

  telemetry.observe(0x101, 0x100, -70, 100);
  telemetry.observe(0x101, 0x102, -50, 200);
  telemetry.observe(0x101, 0x102, -90, 300);
  const PeerTelemetryEntry *peer = telemetry.get(0x101);
  assert(peer != nullptr);
  assert(peer->uplinkId == 0x102);
  assert(peer->latestRssi == -90);
  assert(peer->minimumRssi == -90);
  assert(peer->maximumRssi == -50);
  assert(peer->smoothedRssi == -71);
  assert(peer->samples == 3);
  assert(peer->lastSeenMs == 300);

  for (uint16_t index = 0; index < TUBES_PEER_TELEMETRY_CAPACITY - 1; index++) {
    telemetry.observe(static_cast<uint16_t>(0x200 + index), 0x100, -60, static_cast<uint32_t>(400 + index));
  }
  assert(telemetry.count() == TUBES_PEER_TELEMETRY_CAPACITY);
  assert(telemetry.entry(TUBES_PEER_TELEMETRY_CAPACITY) == nullptr);

  telemetry.observe(0x999, 0x100, -40, 1000);
  assert(telemetry.count() == TUBES_PEER_TELEMETRY_CAPACITY);
  assert(telemetry.get(0x101) == nullptr);
  assert(telemetry.get(0x999) != nullptr);
}
// AI: end
