#include <assert.h>
#include <stdint.h>

#include "usermods/Tubes/mobile_conductor_route.h"

// AI: below section was generated by an AI
// Exercises route choice, expiry, bounds, ordering, and beat-state isolation.
int main() {
  MobileRouteModel route;
  MobileRouteAdvertisement first = makeMobileRouteAdvertisement(900, 901, 0x12345678, 10, 0, 0, 0x10203040);
  uint32_t beatFrame = 0x11223344;

  assert(route.observe(first, -50, 100, beatFrame));
  assert(route.valid(100));
  assert(route.shell(100) == 1);
  assert(route.parentId() == 901);
  assert(beatFrame == 0x11223344);

  MobileRouteAdvertisement worse = makeMobileRouteAdvertisement(900, 902, 0x12345678, 11, 1, 60, 0x10203040);
  assert(!route.observe(worse, -80, 200, beatFrame));
  assert(route.parentId() == 901);

  MobileRouteAdvertisement better = makeMobileRouteAdvertisement(900, 903, 0x12345678, 12, 0, 0, 0x10203040);
  assert(!route.observe(better, -35, 300, beatFrame));
  assert(!route.observe(better, -35, 1799, beatFrame));
  better.sequence++;
  assert(route.observe(better, -35, 1800, beatFrame));
  assert(route.parentId() == 903);
  assert(beatFrame == 0x11223344);

  MobileRouteAdvertisement oldSequence = better;
  oldSequence.sequence--;
  assert(!route.observe(oldSequence, -30, 1900, beatFrame));
  MobileRouteAdvertisement otherSession = better;
  otherSession.sessionNonce++;
  otherSession.sequence = 1;
  assert(!route.observe(otherSession, -30, 2000, beatFrame));

  MobileRouteAdvertisement capped = makeMobileRouteAdvertisement(900, 904, 0x12345678, 14,
    MOBILE_ROUTE_MAX_HOP, MOBILE_ROUTE_MAX_COST, 0x10203040);
  assert(!route.observe(capped, -127, 2100, beatFrame));
  assert(nextMobileRouteHop(capped.hop) == MOBILE_ROUTE_MAX_HOP);
  assert(addMobileRouteCost(capped.routeCost, 255) == MOBILE_ROUTE_MAX_COST);

  assert(!route.valid(4801));
  assert(route.shell(4801) == MOBILE_ROUTE_SHELL_UNKNOWN);
  assert(beatFrame == 0x11223344);
}
// AI: end
