#include <assert.h>
#include <stdint.h>
#include <string.h>

#include "usermods/Tubes/mobile_conductor_route.h"
#include "tools/fixtures/tubes_golden_packets.h"

// AI: below section was generated by an AI
// Exercises route choice, expiry, bounds, conductor-wide ordering, and relay competition.
int main() {
  const MobileRouteAdvertisement golden = makeMobileRouteAdvertisement(
    0x1234, 0x5678, 0x89abcdef, 0x01020304, 3, 42);
  assert(sizeof(golden) == sizeof(TUBES_GOLDEN_ROUTE_V1));
  assert(memcmp(&golden, TUBES_GOLDEN_ROUTE_V1, sizeof(golden)) == 0);

  MobileRouteModel route;
  MobileRouteAdvertisement first = makeMobileRouteAdvertisement(900, 901, 0x12345678, 10, 0, 0);

  assert(route.observe(first, -80, 100));
  assert(route.valid(100));
  assert(route.shell(100) == 1);
  assert(route.parentId() == 901);

  MobileRouteAdvertisement strongerRelay = makeMobileRouteAdvertisement(900, 902, 0x12345678, 10, 0, 0);
  assert(!route.observe(strongerRelay, -35, 200));
  assert(route.parentId() == 901);

  // The selected parent's repeat refreshes it without erasing a better candidate.
  assert(!route.observe(first, -80, 800));

  // Rehearing the candidate is useful path freshness and may complete dwell.
  assert(route.observe(strongerRelay, -35, 1700));
  assert(route.parentId() == 902);

  // The selected parent's exact repeat intentionally refreshes route freshness only.
  assert(!route.observe(strongerRelay, -35, 4000));
  assert(route.valid(6501));

  MobileRouteAdvertisement sameSequenceOtherRelay = strongerRelay;
  sameSequenceOtherRelay.senderId = 903;
  assert(!route.observe(sameSequenceOtherRelay, -30, 4100));
  assert(route.sequence() == 10);

  MobileRouteAdvertisement oldSequence = strongerRelay;
  oldSequence.sequence--;
  assert(!route.observe(oldSequence, -30, 4200));
  MobileRouteAdvertisement otherSession = strongerRelay;
  otherSession.sessionNonce++;
  otherSession.sequence = 1;
  assert(!route.observe(otherSession, -30, 4300));

  // Alternate relays of one conductor-wide sequence do not add packet-loss cost.
  MobileRouteModel lossRoute;
  MobileRouteAdvertisement sequence20 = makeMobileRouteAdvertisement(900, 910, 0x87654321, 20, 0, 0);
  assert(lossRoute.observe(sequence20, -50, 100));
  const uint16_t baseCost = lossRoute.cost();
  MobileRouteAdvertisement sequence20Alternate = sequence20;
  sequence20Alternate.senderId = 911;
  assert(!lossRoute.observe(sequence20Alternate, -50, 200));
  sequence20.sequence = 22;
  assert(!lossRoute.observe(sequence20, -50, 300));
  assert(lossRoute.cost() == addMobileRouteCost(baseCost, MOBILE_ROUTE_LOSS_COST));

  MobileRouteAdvertisement capped = makeMobileRouteAdvertisement(900, 904, 0x12345678, 14,
    MOBILE_ROUTE_MAX_HOP, MOBILE_ROUTE_MAX_COST);
  assert(!route.observe(capped, -127, 4400));
  assert(nextMobileRouteHop(capped.hop) == MOBILE_ROUTE_MAX_HOP);
  assert(addMobileRouteCost(capped.routeCost, 255) == MOBILE_ROUTE_MAX_COST);

  assert(!route.valid(7101));
  assert(route.shell(7101) == MOBILE_ROUTE_SHELL_UNKNOWN);
}
// AI: end
