#include <assert.h>
#include <stdint.h>
#include <string.h>

using byte = uint8_t;
typedef uint8_t CommandId;

#define TUBES_ALLOW_UNSUPPORTED_ENDIAN_HOST_TEST
#include "usermods/Tubes/node_message.h"
#include "tools/fixtures/tubes_golden_packets.h"

// AI: below section was generated by an AI
int main() {
#if defined(__BYTE_ORDER__) && __BYTE_ORDER__ != __ORDER_LITTLE_ENDIAN__
  return 77;
#else
  NodeMessage message = {};
  message.header.id = 0x1234;
  message.header.uplinkId = 0x5678;
  message.header.version = CURRENT_NODE_VERSION;
  message.recipients = RECIPIENTS_ALL;
  message.timebase = 0x01020304;
  message.command = 0x20;

  const uint8_t canonicalState[] = {
    0x00, 0x78, 0x00, 0x00, 0x44, 0x33, 0x22, 0x11,
    0x05, 0x00, 0x17, 0x06, 0x09, 0x00, 0x07, 0x00,
    0x0b, 0x00, 0x02, 0x01, 0x10, 0x00, 0x00, 0x00,
    0x00, 0x80, 0x00, 0x00, 0x88, 0x77, 0x66, 0x55,
    0x09, 0x00, 0x18, 0x03, 0x0a, 0x00, 0x0d, 0x00,
    0x0c, 0x01, 0x04, 0x08, 0x20
  };
  memcpy(message.data, canonicalState, sizeof(canonicalState));

  assert(sizeof(message) == sizeof(TUBES_GOLDEN_NODE_V2_STATE));
  assert(memcmp(&message, TUBES_GOLDEN_NODE_V2_STATE, sizeof(message)) == 0);
  return 0;
#endif
}
// AI: end
